// Generated by scripts/data-map.mjs from the saved schema. Do not edit.
export const dataMapSchema = [
  {
    "name": "accounts",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "code"
      },
      {
        "name": "attribute"
      },
      {
        "name": "name"
      },
      {
        "name": "sort_order"
      }
    ]
  },
  {
    "name": "aggregation_groups",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "display_name"
      },
      {
        "name": "name"
      },
      {
        "name": "required_key"
      },
      {
        "name": "sort_order"
      }
    ]
  },
  {
    "name": "aggregation_members",
    "columns": [
      {
        "name": "parent_id",
        "reference": "aggregation_groups.id"
      },
      {
        "name": "account_id",
        "reference": "accounts.id"
      },
      {
        "name": "group_id",
        "reference": "aggregation_groups.id"
      },
      {
        "name": "sign"
      },
      {
        "name": "position"
      }
    ]
  },
  {
    "name": "amount_overrides",
    "columns": [
      {
        "name": "row_id",
        "reference": "initiative_rows.id"
      },
      {
        "name": "month"
      },
      {
        "name": "amount_yen"
      },
      {
        "name": "revision"
      }
    ]
  },
  {
    "name": "data_history",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "recorded_at"
      },
      {
        "name": "snapshot"
      }
    ]
  },
  {
    "name": "data_history_state",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "version"
      },
      {
        "name": "next_id"
      },
      {
        "name": "dirty_since"
      },
      {
        "name": "saved_at"
      }
    ]
  },
  {
    "name": "departments",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "name"
      }
    ]
  },
  {
    "name": "expansions",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "code"
      },
      {
        "name": "name"
      }
    ]
  },
  {
    "name": "industries",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "code"
      },
      {
        "name": "name"
      }
    ]
  },
  {
    "name": "initiative_amounts",
    "columns": [
      {
        "name": "row_id",
        "reference": "initiative_rows.id"
      },
      {
        "name": "month"
      },
      {
        "name": "amount_yen"
      },
      {
        "name": "revision"
      }
    ]
  },
  {
    "name": "initiative_rows",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "initiative_id",
        "reference": "initiatives.id"
      },
      {
        "name": "account_id",
        "reference": "accounts.id"
      },
      {
        "name": "sort_order"
      },
      {
        "name": "revision"
      }
    ]
  },
  {
    "name": "initiatives",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "name"
      },
      {
        "name": "note"
      },
      {
        "name": "expansion_id",
        "reference": "expansions.id"
      },
      {
        "name": "industry_id",
        "reference": "industries.id"
      },
      {
        "name": "department_id",
        "reference": "departments.id"
      },
      {
        "name": "period_type_id",
        "reference": "period_types.id"
      },
      {
        "name": "primary_start_year_month"
      },
      {
        "name": "confirmed_start_year_month"
      },
      {
        "name": "sort_order"
      },
      {
        "name": "revision"
      }
    ]
  },
  {
    "name": "kind_selections",
    "columns": [
      {
        "name": "screen"
      },
      {
        "name": "first_kind"
      },
      {
        "name": "second_kind"
      }
    ]
  },
  {
    "name": "period_types",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "name"
      },
      {
        "name": "start_month_rule"
      }
    ]
  },
  {
    "name": "plan",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "fiscal_year"
      },
      {
        "name": "created_at"
      },
      {
        "name": "updated_at"
      }
    ]
  },
  {
    "name": "previous_amounts",
    "columns": [
      {
        "name": "id"
      },
      {
        "name": "account_id",
        "reference": "accounts.id"
      },
      {
        "name": "industry_id",
        "reference": "industries.id"
      },
      {
        "name": "department_id",
        "reference": "departments.id"
      },
      {
        "name": "month"
      },
      {
        "name": "amount_yen"
      },
      {
        "name": "revision"
      }
    ]
  },
  {
    "name": "triadic_metadata",
    "columns": [
      {
        "name": "key"
      },
      {
        "name": "value"
      }
    ]
  }
] as const;
