import assert from "node:assert/strict";

export async function verifyAutoSave(api) {
  const { AutoSave, createTriadicDatabase, changeAccountMaster, registerInitiative, updateInitiative, readPlanContents, openTriadicDatabase, saveInitiativeUpdate } = api;
  const writes = [];
  let complete;
  const queue = new AutoSave(async draft => { writes.push(draft); await new Promise(resolve => { complete = resolve; }); }, 10000);
  queue.begin({ value: "before" });
  queue.change({ value: "first" });
  const first = queue.flush();
  queue.change({ value: "latest" });
  await queue.flush();
  assert.equal(writes.length, 1, "同時書き込みしない");
  complete(); await first;
  assert.equal(queue.getSnapshot().draft.value, "latest");
  assert.equal(queue.getSnapshot().pending, true);
  const next = queue.flush(); complete(); await next;
  assert.deepEqual(writes.map(item => item.value), ["first", "latest"]);
  assert.equal(queue.getSnapshot().pending, false);
  queue.pause(); queue.change({ value: "変換中" }); await queue.flush();
  assert.equal(writes.length, 2, "日本語変換中は確定しない");
  queue.resume(); queue.discard(); queue.end();
  let fail = true;
  const retry = new AutoSave(async () => { if (fail) throw new Error("保存失敗"); }, 10000);
  retry.begin("original"); retry.change("edited"); await retry.flush();
  assert.equal(retry.getSnapshot().draft, "edited");
  assert.equal(retry.getSnapshot().pending, true);
  assert.equal(retry.getSnapshot().error, "保存失敗");
  fail = false; await retry.flush();
  retry.change("unsaved"); retry.discard();
  assert.equal(retry.getSnapshot().draft, "edited", "直近の保存成功まで戻す");
  retry.end();

  let bytes = await createTriadicDatabase();
  bytes = (await changeAccountMaster(bytes, { type: "add", accountCode: "100", accountName: "売上", accountType: "sales" })).bytes;
  const draft = { name: "施策", note: "備考", expansionId: 1, industryId: 1, departmentId: 1, fiscalYear: "2026", rows: [{ accountId: 1, amounts: { 4: "100", 5: "0" } }, { accountId: 1, amounts: { 4: "25.5" } }] };
  bytes = await registerInitiative(bytes, draft);
  bytes = await registerInitiative(bytes, { ...draft, name: "別施策" });
  const before = await readPlanContents(bytes);
  const original = before.initiatives[0];
  const edited = { name: "更新施策", note: "更新備考", expansionId: 1, industryId: 1, departmentId: 1, fiscalYear: "2026", rows: original.rows.map((row, index) => ({ ...row, amounts: index ? { 4: "-25.5" } : { 4: "200", 6: "0" } })) };
  const updatedBytes = await updateInitiative(bytes, original.id, 2026, edited);
  const updated = await readPlanContents(updatedBytes);
  assert.equal(updated.initiatives[0].name, "更新施策");
  assert.equal(updated.initiatives[0].fiscalYear, 2026);
  assert.equal(updated.initiatives[0].rows[0].amounts[4], "200");
  assert.equal(updated.initiatives[0].rows[0].amounts[5], "0");
  assert.equal(Object.keys(updated.initiatives[0].rows[0].amounts).length, 12);
  assert.deepEqual(updated.initiatives[0].months[4], { sales: 174500, expense: 0, profit: 174500 });
  assert.deepEqual(updated.initiatives[1], before.initiatives[1], "別の施策に影響しない");
  assert.deepEqual(await readPlanContents(bytes), before);
  await assert.rejects(updateInitiative(updatedBytes, original.id, 2026, { ...edited, name: "別施策" }), /同じ施策名/);
  await assert.rejects(updateInitiative(updatedBytes, original.id, 2026, { ...edited, invalidNumbers: true }), /有効な数値/);
  for (const kind of [1, 2]) {
    const cell = { row: 0, column: 0 };
    const bad = api.changeInitiativeCell({ ...edited, invalidNumbers: false }, kind, cell, "", { original: "200", inherited: kind === 2 });
    await assert.rejects(registerInitiative(updatedBytes, { ...bad, name: "不正な新規入力" }), /有効な数値/);
    let storedBytes = updatedBytes;
    const inputQueue = new AutoSave(async value => { storedBytes = await updateInitiative(storedBytes, original.id, 2026, value); }, 10000);
    inputQueue.begin(edited); inputQueue.change(bad); await inputQueue.flush();
    assert.match(inputQueue.getSnapshot().error, /有効な数値/);
    const other = api.pasteInitiativeGrid(bad, kind === 1 ? 2 : 1, { row: 1, column: 1 }, "8");
    inputQueue.change(other); await inputQueue.flush();
    assert.equal(inputQueue.getSnapshot().pending, true); assert.match(inputQueue.getSnapshot().error, /有効な数値/);
    assert.deepEqual(storedBytes, updatedBytes, "別種別の正常入力で不正な空欄を0として保存しない");
    inputQueue.change(api.cancelInitiativeCell(other, kind, cell, { original: "0", inherited: false })); await inputQueue.flush();
    assert.equal(inputQueue.getSnapshot().pending, false);
    assert.equal((await readPlanContents(storedBytes)).initiatives[0].rows[0].amounts[4], "200");
    inputQueue.end();
  }
  const zeroed = await updateInitiative(updatedBytes, original.id, 2026, { ...edited, rows: [{ ...edited.rows[0], amounts: {} }, edited.rows[1]] });
  assert.equal((await readPlanContents(zeroed)).initiatives[0].rows[0].amounts[4], "0");
  const extended = { ...edited, rows: [...edited.rows, { id: "追加行の識別子", accountId: 1, amounts: {} }] };
  const extendedBytes = await updateInitiative(updatedBytes, original.id, 2026, extended);
  extended.rows[2].amounts[4] = "10";
  const again = await updateInitiative(extendedBytes, original.id, 2026, extended);
  assert.equal((await readPlanContents(again)).initiatives[0].rows.length, 3, "保存直後の新しい行を重複作成しない");
  let stored = bytes;
  let shouldFail = false;
  const handle = { name: "test.triadic", async getFile() { return new File([stored], this.name); }, async createWritable() {
    let pending;
    return { async write(value) { if (shouldFail) throw new Error("書込失敗"); pending = value; }, async close() { stored = new Uint8Array(pending); }, async abort() {} };
  } };
  const plan = { ...before, bytes, name: handle.name, handle };
  const saved = await saveInitiativeUpdate(plan, original.id, 2026, edited);
  assert.deepEqual(saved.bytes, stored);
  await assert.rejects(saveInitiativeUpdate(plan, original.id, 2026, edited), /別の操作で更新/);
  shouldFail = true;
  await assert.rejects(saveInitiativeUpdate(saved, original.id, 2026, { ...edited, note: "失敗" }), /書込失敗/);
  assert.deepEqual(saved.bytes, stored);
  shouldFail = false;
  stored = new Uint8Array();
  const destination = await saveInitiativeUpdate({ ...plan, destinationBytes: stored }, original.id, 2026, edited);
  assert.equal(destination.initiatives[0].name, "更新施策", "新しい保存先でも元の計画から更新する");
  console.log("PASS: automatic save sequencing, composition, retry, initiative updates, blank/zero, shared row identity and conflicts");
}
