import assert from "node:assert/strict";

export async function verifyDepartmentData(api) {
  const { createTriadicDatabase, readPlanContents, changeDepartmentMaster, saveDepartmentMaster, openTriadicDatabase, registerInitiative, updateInitiative, validateTriadicDatabase } = api;
  const bytes = await createTriadicDatabase();
  const initial = await readPlanContents(bytes);
  assert.deepEqual(initial.departments.map(item => item.departmentName), ["部署A", "部署B"]);
  let changed = await changeDepartmentMaster(bytes, { type: "add", departmentName: " 部署C ", industryIds: [1] });
  assert.equal((await readPlanContents(changed)).departments.at(-1).departmentName, "部署C");
  for (const departmentName of ["", " ", "　"]) await assert.rejects(changeDepartmentMaster(bytes, { type: "add", departmentName }), /部署名/);
  await assert.rejects(changeDepartmentMaster(bytes, { type: "add", departmentName: "部署A", industryIds: [1] }), /同じ部署名/);
  changed = await changeDepartmentMaster(changed, { type: "update", id: 1, departmentName: "部署改定" });
  changed = await changeDepartmentMaster(changed, { type: "delete", id: 2 });
  assert.deepEqual((await readPlanContents(changed)).departments.map(item => item.departmentName), ["部署改定", "部署C"]);
  await assert.rejects(changeDepartmentMaster(changed, { type: "delete", id: 999 }), /見つかりません/);
  const draft = { name: "部署選択確認", note: "保持確認", fiscalYear: "2026", expansionId: initial.expansions[0].id, industryId: initial.industries[0].id, departmentId: 1, rows: [{ accountId: initial.accounts[0].id, amounts: { 4: "1.001" } }] };
  let assigned = await registerInitiative(bytes, draft);
  draft.rows[0].id = (await readPlanContents(assigned)).initiatives[0].rows[0].id;
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 1);
  await assert.rejects(changeDepartmentMaster(assigned, { type: "delete", id: 1 }), /使用中/);
  await assert.rejects(registerInitiative(bytes, { ...draft, departmentId: 999 }), /部署名/);
  assigned = await updateInitiative(assigned, 1, 2026, { ...draft, departmentId: 2 });
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 2);
  assigned = await changeDepartmentMaster(assigned, { type: "update", id: 2, departmentName: "部署B改定" });
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 2);
  await assert.rejects(updateInitiative(assigned, 1, 2026, { ...draft, departmentId: null }), /部署名/);
  let empty = bytes;
  for (const item of initial.departments) empty = await changeDepartmentMaster(empty, { type: "delete", id: item.id });
  assert.deepEqual((await readPlanContents(empty)).departments, []);
  const malformed = await openTriadicDatabase(bytes);
  malformed.exec("DROP TABLE departments");
  const invalid = malformed.export(); malformed.close();
  await assert.rejects(validateTriadicDatabase(invalid));
  let stored = bytes;
  const handle = { name: "department.triadic", async getFile() { return new File([stored], this.name); }, async createWritable() {
    let pending; return { async write(value) { pending = value; }, async close() { stored = new Uint8Array(pending); }, async abort() {} };
  } };
  const plan = { ...initial, bytes, handle, name: handle.name };
  const noPicker = () => { throw new Error("不要な保存先選択"); };
  const saved = await saveDepartmentMaster(plan, { type: "add", departmentName: "保存確認", industryIds: [1] }, noPicker);
  assert.deepEqual((await readPlanContents(stored)).departments, saved.departments);
  await assert.rejects(saveDepartmentMaster(plan, { type: "add", departmentName: "競合確認", industryIds: [1] }, noPicker), /保存先のファイルが更新/);
  const before = stored.slice();
  const failing = { ...handle, async createWritable() { return { async write() { throw new Error("保存失敗"); }, async close() {}, async abort() {} }; } };
  await assert.rejects(saveDepartmentMaster({ ...saved, handle: failing }, { type: "delete", id: 1 }, noPicker), /保存失敗/);
  assert.deepEqual(stored, before);
  await assert.rejects(saveDepartmentMaster({ ...saved, handle: failing }, { type: "update", id: 1, departmentName: "部署A", industryIds: [2, 3] }, noPicker), /保存失敗/);
  assert.deepEqual(stored, before);
  await assert.rejects(saveDepartmentMaster({ ...plan, handle: undefined }, { type: "add", departmentName: "キャンセル確認", industryIds: [1] }, async () => { throw new DOMException("キャンセル", "AbortError"); }), { name: "AbortError" });
  assert.deepEqual((await readPlanContents(bytes)).departments, initial.departments);
  // Multiple industries, shared memberships, rejected edits and atomic persistence.
  let linked = await changeDepartmentMaster(bytes, { type: "update", id: 1, departmentName: "部署A", industryIds: [1, 2] });
  linked = await changeDepartmentMaster(linked, { type: "update", id: 2, departmentName: "部署B", industryIds: [2] });
  assert.deepEqual((await readPlanContents(linked)).departments.map(d => d.industryIds), [[1, 2], [2]]);
  for (const industryIds of [[], [1, 1], [999], [1.5]]) await assert.rejects(changeDepartmentMaster(linked, { type: "update", id: 1, departmentName: "部署A", industryIds }), /業種/);
  await assert.rejects(changeDepartmentMaster(linked, { type: "add", departmentName: "所属なし", industryIds: [] }), /業種/);
  await assert.rejects(registerInitiative(linked, { ...draft, departmentId: 2, industryId: 1 }), /部署に設定/);
  linked = await registerInitiative(linked, { ...draft, industryId: 2 });
  await assert.rejects(changeDepartmentMaster(linked, { type: "update", id: 1, departmentName: "部署A", industryIds: [1] }), /使用中/);
  await assert.rejects(api.changeIndustryMaster(linked, { type: "delete", id: 1 }), /部署に設定/);
  const previousInput = { industryId: 2, departmentId: 2, rows: [{ accountId: initial.accounts[0].id, amounts: { 4: "1.001" } }] };
  await assert.rejects(api.savePreviousAmounts(linked, { ...previousInput, industryId: 1 }), /部署に設定/);
  const withPrevious = await api.savePreviousAmounts(linked, previousInput);
  await assert.rejects(changeDepartmentMaster(withPrevious, { type: "update", id: 2, departmentName: "部署B", industryIds: [1] }), /使用中/);
  const exportContents = await readPlanContents(linked);
  const workbook = api.createPreviousWorkbook(exportContents, [{ industryId: 1, departmentId: 1 }]);
  workbook.worksheets[0].getCell("C4").value = 1;
  const excelBytes = await api.serializeWorkbook(workbook);
  const patches = await api.parsePreviousWorkbook(excelBytes, exportContents);
  const snapshot = await api.createBusinessSnapshot(linked);
  const relinked = await changeDepartmentMaster(linked, { type: "update", id: 1, departmentName: "部署A改名", industryIds: [2, 3] });
  assert.deepEqual((await readPlanContents(relinked)).departments[0].industryIds, [2, 3]);
  await assert.rejects(api.parsePreviousWorkbook(excelBytes, await readPlanContents(relinked)), /業種設定/);
  await assert.rejects(api.changePlanSettings(relinked, { type: "previous-import", patches }), /部署に設定/);
  assert.deepEqual((await readPlanContents(relinked)).initiatives, (await readPlanContents(linked)).initiatives);
  assert.deepEqual((await readPlanContents(await api.applyOperationSnapshot(relinked, snapshot))).departments, (await readPlanContents(linked)).departments);
  const invalidPair = { industryId: 1, departmentId: 2 };
  const linkedContents = await readPlanContents(linked);
  assert.throws(() => api.createPreviousWorkbook(linkedContents, [invalidPair]), /部署に設定/);
  console.log("PASS: department CRUD, defaults, initiative assignment, failed/cancelled/conflicting saves");
}
