import assert from "node:assert/strict";

export async function verifyDepartmentData(api) {
  const { createTriadicDatabase, readPlanContents, changeDepartmentMaster, saveDepartmentMaster, openTriadicDatabase, registerInitiative, updateInitiative, validateTriadicDatabase } = api;
  const bytes = await createTriadicDatabase();
  const initial = await readPlanContents(bytes);
  assert.deepEqual(initial.departments.map(item => item.departmentName), ["部署A", "部署B"]);
  let changed = await changeDepartmentMaster(bytes, { type: "add", departmentName: " 部署C " });
  assert.equal((await readPlanContents(changed)).departments.at(-1).departmentName, "部署C");
  for (const departmentName of ["", " ", "　"]) await assert.rejects(changeDepartmentMaster(bytes, { type: "add", departmentName }), /部署名/);
  await assert.rejects(changeDepartmentMaster(bytes, { type: "add", departmentName: "部署A" }), /同じ部署名/);
  changed = await changeDepartmentMaster(changed, { type: "update", id: 1, departmentName: "部署改定" });
  changed = await changeDepartmentMaster(changed, { type: "delete", id: 2 });
  assert.deepEqual((await readPlanContents(changed)).departments.map(item => item.departmentName), ["部署改定", "部署C"]);
  await assert.rejects(changeDepartmentMaster(changed, { type: "delete", id: 999 }), /見つかりません/);
  const draft = { name: "部署選択確認", note: "保持確認", fiscalYear: "2026", expansionId: initial.expansions[0].id, departmentId: 1, rows: [{ accountId: initial.accounts[0].id, amounts: { 4: "1.001" } }] };
  let assigned = await registerInitiative(bytes, draft);
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 1);
  await assert.rejects(changeDepartmentMaster(assigned, { type: "delete", id: 1 }), /使用中/);
  await assert.rejects(registerInitiative(bytes, { ...draft, departmentId: 999 }), /部署名/);
  assigned = await updateInitiative(assigned, 1, 2026, { ...draft, departmentId: 2 });
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 2);
  assigned = await changeDepartmentMaster(assigned, { type: "update", id: 2, departmentName: "部署B改定" });
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 2);
  assigned = await updateInitiative(assigned, 1, 2026, { ...draft, departmentId: null });
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, null);
  let empty = bytes;
  for (const item of initial.departments) empty = await changeDepartmentMaster(empty, { type: "delete", id: item.id });
  assert.deepEqual((await readPlanContents(empty)).departments, []);
  const legacyDb = await openTriadicDatabase(assigned);
  legacyDb.exec("ALTER TABLE initiatives DROP COLUMN department_id; DROP TABLE departments; PRAGMA user_version = 7; UPDATE triadic_metadata SET value = '7' WHERE key = 'format_version';");
  const legacy = legacyDb.export(); legacyDb.close();
  const oldContents = await readPlanContents(legacy);
  assert.deepEqual(oldContents.departments, initial.departments);
  assert.equal(oldContents.initiatives[0].departmentId, null);
  const migrated = await changeDepartmentMaster(legacy, { type: "update", id: 1, departmentName: "移行確認" });
  assert.deepEqual((await readPlanContents(migrated)).initiatives, oldContents.initiatives);
  const unchanged = await openTriadicDatabase(legacy);
  assert.equal(unchanged.exec("PRAGMA user_version")[0].values[0][0], 7); unchanged.close();
  const malformed = await openTriadicDatabase(bytes);
  malformed.exec("DROP TABLE departments");
  const invalid = malformed.export(); malformed.close();
  await assert.rejects(validateTriadicDatabase(invalid));
  let stored = bytes;
  const handle = { name: "department.triadic", async getFile() { return new File([stored], this.name); }, async createWritable() {
    let pending; return { async write(value) { pending = value; }, async close() { stored = new Uint8Array(pending); }, async abort() {} };
  } };
  const plan = { ...initial, bytes, handle, name: handle.name };
  const noPicker = () => { throw new Error("不要な保存先選択"); };
  const saved = await saveDepartmentMaster(plan, { type: "add", departmentName: "保存確認" }, noPicker);
  assert.deepEqual((await readPlanContents(stored)).departments, saved.departments);
  await assert.rejects(saveDepartmentMaster(plan, { type: "add", departmentName: "競合確認" }, noPicker), /別の操作で更新/);
  const before = stored.slice();
  const failing = { ...handle, async createWritable() { return { async write() { throw new Error("保存失敗"); }, async close() {}, async abort() {} }; } };
  await assert.rejects(saveDepartmentMaster({ ...saved, handle: failing }, { type: "delete", id: 1 }, noPicker), /保存失敗/);
  assert.deepEqual(stored, before);
  await assert.rejects(saveDepartmentMaster({ ...plan, handle: undefined }, { type: "add", departmentName: "キャンセル確認" }, async () => { throw new DOMException("キャンセル", "AbortError"); }), { name: "AbortError" });
  assert.deepEqual((await readPlanContents(bytes)).departments, initial.departments);
  console.log("PASS: department CRUD, defaults, initiative assignment, migration and failed/cancelled/conflicting saves");
}
