import assert from "node:assert/strict";
export async function verifyDetails(api) {
  let bytes = await api.createTriadicDatabase();
  const initial = await api.readPlanContents(bytes);
  const sales = initial.accounts.find(a => a.accountType === "sales");
  const expense = initial.accounts.find(a => a.accountType === "expense");
  const draft = { name: "明細検証", note: "", expansionId: initial.expansions[0].id, fiscalYear: "2026", rows: [{ accountId: sales.id, amounts: { 4: "0.001" } }, { accountId: sales.id, amounts: { 4: "2" } }] };
  bytes = await api.registerInitiative(bytes, draft);
  bytes = await api.registerInitiative(bytes, { ...draft, name: "別施策", fiscalYear: "2027" });
  let contents = await api.readPlanContents(bytes);
  assert.equal(contents.details.length, 48);
  assert.deepEqual(contents.details.slice(0,12).map(row => row.month), [4,5,6,7,8,9,10,11,12,1,2,3]);
  const source = bytes.slice();
  const target = contents.details[0];
  bytes = await api.changeDetail(bytes, { target, field: "amount", value: "-0.001" });
  let after = await api.readPlanContents(bytes);
  assert.equal(after.details.filter(row => row.amount !== contents.details.find(item => item.id === row.id).amount).length, 1);
  assert.equal(after.details[0].sales, "-0.001");
  await assert.rejects(api.changeDetail(bytes, { target, field: "amount", value: "10" }), /変更されています/);
  assert.deepEqual(await api.readPlanContents(source), contents, "元のバイト列は変更しない");
  const sameRow = after.details[0];
  bytes = await api.changeDetail(bytes, { target: sameRow, field: "accountId", value: String(expense.id) });
  after = await api.readPlanContents(bytes);
  assert.equal(after.details.filter(row => row.accountId === expense.id).length, 12);
  assert.equal(after.details[12].accountId, sales.id, "同科目の別入力行を変更しない");
  assert.equal(after.details[0].sales, "0"); assert.equal(after.details[0].profit, "0.001");
  bytes = await api.changeDetail(bytes, { target: after.details[0], field: "name", value: "変更施策" });
  after = await api.readPlanContents(bytes);
  assert.equal(after.details.filter(row => row.initiativeName === "変更施策").length, 24);
  assert.equal(after.details.filter(row => row.initiativeName === "別施策").length, 24);
  bytes = await api.changeDetail(bytes, { target: after.details[0], field: "fiscalYear", value: "2028" });
  after = await api.readPlanContents(bytes);
  const owned = after.details.filter(row => row.initiativeName === "変更施策");
  assert.equal(owned.find(row => row.month === 1).year, 2029);
  assert.equal(after.details[0].initiativeName, "別施策", "年度昇順を保つ");
  const current = owned[0];
  for (const [field, value, reason] of [["name", "別施策", /同じ施策名/], ["fiscalYear", "9999", /年度/], ["accountId", "999999", /登録科目/], ["amount", "0.0001", /3桁/], ["amount", "9007199254740.992", /範囲/], ["expansionId", "", /展開名/]]) {
    await assert.rejects(api.changeDetail(bytes, { target: current, field, value }), reason);
  }
  const zeroed = await api.changeDetail(bytes, { target: current, field: "amount", value: "" });
  assert.equal((await api.readPlanContents(zeroed)).details.find(row => row.id === current.id).amount, "0");
  assert.equal(api.amountToYen("9007199254740.991"), 9007199254740991);
  assert.equal(api.yenToAmount(9007199254740991), "9007199254740.991");
  const db = await api.openTriadicDatabase(bytes);
  assert.throws(() => db.run("INSERT INTO initiative_amounts(row_id,month) VALUES (?,4)",[current.rowId]), /UNIQUE/);
  db.run("DELETE FROM initiative_amounts WHERE id = ?",[current.id]);
  const broken = db.export(); db.close();
  await assert.rejects(api.validateTriadicDatabase(broken), /読み込めません/);
  const legacy = await api.asLegacyTestPlan(source);
  let migrationWrites = 0;
  const originalHandle = { name: "old.triadic", async getFile() { return new File([legacy], this.name); }, async createWritable() { migrationWrites++; throw new Error("元ファイルを書き換えない"); } };
  const originalPlan = { ...await api.readPlanContents(legacy), bytes: legacy, name: originalHandle.name, handle: originalHandle };
  await assert.rejects(api.saveDetailChange(originalPlan, { target, field: "amount", value: "1" }), /別名の保存先/);
  assert.equal(migrationWrites, 0);
  const legacyDb = await api.openTriadicDatabase(legacy);
  legacyDb.run("INSERT INTO periods(budget_id,year,month) VALUES(1,2040,4)");
  legacyDb.run("INSERT INTO details(budget_id,period_id,initiative_id,account_id,entry_row_id) SELECT 1,MAX(p.id),?, ?, ? FROM periods p",[target.initiativeId,target.accountId,target.rowId]);
  const ambiguous = legacyDb.export(); legacyDb.close();
  const ambiguousRead = await api.readPlanContents(ambiguous);
  assert.match(ambiguousRead.migrationError, /複数年度/);
  await assert.rejects(api.changeDetail(ambiguous, { target, field: "amount", value: "1" }), /複数年度/);
  const column = { id: "name", label: "施策名", value: row => row.initiativeName };
  assert.equal(api.applyTableView(after.details,[column],{ sort:null,filters:{name:["別施策"]} }).length,24);
  assert.deepEqual(api.applyTableView(after.details,[column],api.emptyTableView()),after.details);
  const preciseRows = [{ amount: "9007199254740.991" }, { amount: "9007199254740.99" }];
  assert.deepEqual(api.applyTableView(preciseRows, [{ id: "amount", label: "金額", numeric: true, value: row => row.amount }], { sort: { column: "amount", direction: "asc" }, filters: {} }).map(row => row.amount), ["9007199254740.99", "9007199254740.991"]);
  const amountColumn = { id: "amount", label: "金額", amount: true, numeric: true, value: row => row.amount };
  const roundedRows = [{ amount: "1.234" }, { amount: "1.499" }, { amount: "1.5" }, { amount: "-0.001" }];
  assert.deepEqual(api.applyTableView(roundedRows, [amountColumn], { sort: null, filters: { amount: ["1"] } }), roundedRows.slice(0, 2), "表示が同じ金額は同じ候補で絞り込む");
  assert.deepEqual(api.applyTableView(roundedRows, [amountColumn], { sort: { column: "amount", direction: "desc" }, filters: { amount: ["1"] } }), [roundedRows[1], roundedRows[0]], "丸め前の金額で並べ替える");
  let stored = bytes; let writes = 0;
  const handle = { name:"test.triadic", async getFile(){return new File([stored],this.name);}, async createWritable(){ return { async write(){writes++;},async close(){throw new Error("保存失敗");},async abort(){} }; } };
  const plan = { ...after,bytes,name:handle.name,handle };
  await assert.rejects(api.saveDetailChange(plan,{target:current,field:"amount",value:"100"}),/保存失敗/);
  assert.equal(writes,1); assert.deepEqual(stored,bytes); assert.equal(plan.details.find(row=>row.id===current.id).amount,current.amount);
  console.log("PASS: detail ownership scopes, 12 months, fixed calendar, precision, conflicts, invalid mutations, filters and failed saves");
}
