import assert from "node:assert/strict";

export async function verifyKindData(api) {
  const { createTriadicDatabase, readPlanContents, changeKindMaster, saveKindMaster, openTriadicDatabase, validateTriadicDatabase, createSamplePlan, registerInitiative } = api;
  const bytes = await createTriadicDatabase();
  const initial = await readPlanContents(bytes);
  assert.deepEqual(initial.kinds.map(item => item.kindName), ["前年", "一次", "確定", "修正", "見通し"]);
  let changed = await changeKindMaster(bytes, { type: "add", kindName: " 追加種別 " });
  const added = (await readPlanContents(changed)).kinds.at(-1);
  assert.equal(added.kindName, "追加種別");
  for (const kindName of ["", " ", "　", "\n"]) await assert.rejects(changeKindMaster(bytes, { type: "add", kindName }), /種別/);
  await assert.rejects(changeKindMaster(bytes, { type: "add", kindName: "前年" }), /同じ種別/);
  await assert.rejects(changeKindMaster(changed, { type: "update", id: added.id, kindName: "一次" }), /同じ種別/);
  changed = await changeKindMaster(changed, { type: "update", id: added.id, kindName: "改定種別" });
  assert.deepEqual((await readPlanContents(changed)).kinds.at(-1), { id: added.id, kindName: "改定種別" });
  changed = await changeKindMaster(changed, { type: "delete", id: added.id });
  assert.deepEqual((await readPlanContents(changed)).kinds, initial.kinds);
  await assert.rejects(changeKindMaster(changed, { type: "delete", id: 999 }), /見つかりません/);
  await assert.rejects(changeKindMaster(changed, { type: "update", id: 999, kindName: "無効" }), /見つかりません/);
  let empty = bytes;
  for (const item of initial.kinds) empty = await changeKindMaster(empty, { type: "delete", id: item.id });
  const resaved = await registerInitiative(empty, { name: "種別なし", note: "", fiscalYear: "2026", expansionId: initial.expansions[0].id, rows: [{ accountId: initial.accounts[0].id, amounts: { 4: "1.001" } }] });
  assert.deepEqual((await readPlanContents(resaved)).kinds, [], "空のマスタを再補充しない");
  const legacyDb = await openTriadicDatabase(await createSamplePlan(2026));
  legacyDb.exec("DROP TABLE kind_types; PRAGMA user_version = 11; UPDATE triadic_metadata SET value = '11' WHERE key = 'format_version';");
  const legacy = legacyDb.export(); legacyDb.close();
  const old = await readPlanContents(legacy);
  assert.deepEqual(old.kinds, initial.kinds);
  const migrated = await changeKindMaster(legacy, { type: "update", id: 1, kindName: "前年改定" });
  const contents = await readPlanContents(migrated);
  for (const key of ["accounts", "initiatives", "details", "aggregations", "expansions", "industries", "departments", "periodTypes"]) assert.deepEqual(contents[key], old[key], `${key}を保持`);
  assert.equal(contents.formatVersion, 12);
  const untouched = await openTriadicDatabase(legacy);
  assert.equal(untouched.exec("PRAGMA user_version")[0].values[0][0], 11);
  assert.equal(untouched.exec("SELECT name FROM sqlite_master WHERE name = 'kind_types'").length, 0); untouched.close();
  const malformed = await openTriadicDatabase(bytes);
  malformed.exec("DROP TABLE kind_types");
  const invalid = malformed.export(); malformed.close();
  await assert.rejects(validateTriadicDatabase(invalid));
  const blank = await openTriadicDatabase(bytes);
  blank.run("UPDATE kind_types SET name = '　' WHERE id = 1");
  const invalidBlank = blank.export(); blank.close();
  await assert.rejects(validateTriadicDatabase(invalidBlank));
  let stored = legacy;
  const handle = { name: "kind-master.triadic", async getFile() { return new File([stored], this.name); }, async createWritable() {
    let pending; return { async write(value) { pending = value; }, async close() { stored = new Uint8Array(pending); }, async abort() {} };
  } };
  const plan = { ...old, bytes: legacy, handle, name: handle.name };
  const noPicker = () => { throw new Error("不要な保存先選択"); };
  const before = stored.slice();
  const failing = { ...handle, async createWritable() { return { async write() { throw new Error("保存失敗"); }, async close() {}, async abort() {} }; } };
  await assert.rejects(saveKindMaster({ ...plan, handle: failing }, { type: "delete", id: 1 }, noPicker), /保存失敗/);
  assert.deepEqual(stored, before, "失敗した移行では旧ファイルを保持");
  await assert.rejects(saveKindMaster({ ...plan, handle: undefined }, { type: "add", kindName: "キャンセル確認" }, async () => { throw new DOMException("キャンセル", "AbortError"); }), { name: "AbortError" });
  assert.deepEqual(stored, before);
  const saved = await saveKindMaster(plan, { type: "add", kindName: "保存確認" }, noPicker);
  assert.deepEqual((await readPlanContents(stored)).kinds, saved.kinds);
  assert.equal(saved.formatVersion, 12);
  await assert.rejects(saveKindMaster(plan, { type: "add", kindName: "競合確認" }, noPicker), /別の操作で更新/);
  assert.deepEqual((await readPlanContents(bytes)).kinds, initial.kinds);
  console.log("PASS: kind master defaults, CRUD, empty persistence, migration, data protection and failed/cancelled/conflicting saves");
}
