import assert from "node:assert/strict";

export async function verifyPeriodData(api) {
  const { createTriadicDatabase, readPlanContents, changePeriodMaster, savePeriodMaster, openTriadicDatabase, registerInitiative, updateInitiative, validateTriadicDatabase } = api;
  const bytes = await createTriadicDatabase();
  const initial = await readPlanContents(bytes);
  assert.deepEqual(initial.periodTypes.map(item => item.periodName), ["期間差", "新規"]);
  let changed = await changePeriodMaster(bytes, { type: "add", periodName: " 期間C " });
  assert.equal((await readPlanContents(changed)).periodTypes.at(-1).periodName, "期間C");
  for (const periodName of ["", " ", "　"]) await assert.rejects(changePeriodMaster(bytes, { type: "add", periodName }), /期間名/);
  await assert.rejects(changePeriodMaster(bytes, { type: "add", periodName: "期間差" }), /同じ期間名/);
  changed = await changePeriodMaster(changed, { type: "update", id: 1, periodName: "期間改定" });
  changed = await changePeriodMaster(changed, { type: "delete", id: 2 });
  assert.deepEqual((await readPlanContents(changed)).periodTypes.map(item => item.periodName), ["期間改定", "期間C"]);
  await assert.rejects(changePeriodMaster(changed, { type: "delete", id: 999 }), /見つかりません/);
  const draft = { name: "期間選択確認", note: "保持確認", fiscalYear: "2026", expansionId: initial.expansions[0].id, industryId: initial.industries[0].id, departmentId: 2, periodTypeId: 1, rows: [{ accountId: initial.accounts[0].id, amounts: { 4: "1.001" } }] };
  let assigned = await registerInitiative(bytes, draft);
  draft.rows[0].id = (await readPlanContents(assigned)).initiatives[0].rows[0].id;
  assert.equal((await readPlanContents(assigned)).initiatives[0].periodTypeId, 1);
  await assert.rejects(changePeriodMaster(assigned, { type: "delete", id: 1 }), /使用中/);
  await assert.rejects(registerInitiative(bytes, { ...draft, periodTypeId: 999 }), /期間名/);
  assigned = await updateInitiative(assigned, 1, 2026, { ...draft, periodTypeId: 2 });
  assert.equal((await readPlanContents(assigned)).initiatives[0].periodTypeId, 2);
  assert.equal((await readPlanContents(assigned)).initiatives[0].departmentId, 2);
  assigned = await changePeriodMaster(assigned, { type: "update", id: 2, periodName: "新規改定" });
  assert.equal((await readPlanContents(assigned)).initiatives[0].periodTypeId, 2);
  assert.equal((await readPlanContents(assigned)).periodTypes.find(item => item.id === 2).startMonthRule, "new", "改名後もExcel出力へ保存済みの開始年月規則を渡す");
  assigned = await updateInitiative(assigned, 1, 2026, { ...draft, periodTypeId: null });
  assert.equal((await readPlanContents(assigned)).initiatives[0].periodTypeId, null);
  let empty = bytes;
  for (const item of initial.periodTypes) empty = await changePeriodMaster(empty, { type: "delete", id: item.id });
  assert.deepEqual((await readPlanContents(empty)).periodTypes, []);
  const emptySaved = await registerInitiative(empty, { ...draft, periodTypeId: null });
  assert.deepEqual((await readPlanContents(emptySaved)).periodTypes, []);
  const malformed = await openTriadicDatabase(bytes);
  malformed.exec("DROP TABLE period_types");
  const invalid = malformed.export(); malformed.close();
  await assert.rejects(validateTriadicDatabase(invalid));
  let stored = bytes;
  const handle = { name: "period-master.triadic", async getFile() { return new File([stored], this.name); }, async createWritable() {
    let pending; return { async write(value) { pending = value; }, async close() { stored = new Uint8Array(pending); }, async abort() {} };
  } };
  const plan = { ...initial, bytes, handle, name: handle.name };
  const noPicker = () => { throw new Error("不要な保存先選択"); };
  const saved = await savePeriodMaster(plan, { type: "add", periodName: "保存確認" }, noPicker);
  assert.deepEqual((await readPlanContents(stored)).periodTypes, saved.periodTypes);
  await assert.rejects(savePeriodMaster(plan, { type: "add", periodName: "競合確認" }, noPicker), /別の操作で更新/);
  const before = stored.slice();
  const failing = { ...handle, async createWritable() { return { async write() { throw new Error("保存失敗"); }, async close() {}, async abort() {} }; } };
  await assert.rejects(savePeriodMaster({ ...saved, handle: failing }, { type: "delete", id: 1 }, noPicker), /保存失敗/);
  assert.deepEqual(stored, before);
  await assert.rejects(savePeriodMaster({ ...plan, handle: undefined }, { type: "add", periodName: "キャンセル確認" }, async () => { throw new DOMException("キャンセル", "AbortError"); }), { name: "AbortError" });
  assert.deepEqual((await readPlanContents(bytes)).periodTypes, initial.periodTypes);
  console.log("PASS: period master CRUD, defaults, initiative assignment, failed/cancelled/conflicting saves");
}
