import { test, expect, selectClassification, settleMotion, attachImage } from "./fixtures";

test("一つの勘定科目を複数行で選択し、金額を行ごとに保持する", async ({ app }) => {
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await app.getByRole("textbox", { name: "科目コード", exact: true }).fill("501");
  await app.getByRole("textbox", { name: "科目名", exact: true }).fill("消耗品費");
  await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toBeVisible();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "施策入力", exact: true }).click();
  await selectClassification(app.getByRole("spinbutton", { name: "展開名", exact: true }), "コスト");
  await selectClassification(app.getByRole("spinbutton", { name: "業種名", exact: true }), "直営自動車");
  await selectClassification(app.getByRole("spinbutton", { name: "部署名", exact: true }), "部署A");
  const add = app.getByRole("button", { name: "＋ 勘定科目を追加", exact: true });
  for (const index of [1, 2, 3]) {
    if (index > 1) await add.click();
    await expect(add).toBeDisabled();
    await app.getByRole("combobox", { name: `${index}行目の勘定科目` }).selectOption({ label: "501 消耗品費" });
    await expect(add).toBeEnabled();
  }
  const april = app.getByRole("spinbutton", { name: "消耗品費 4月の金額", exact: true });
  await expect(april).toHaveCount(3);
  await april.nth(0).fill("100");
  await april.nth(1).fill("-25.5");
  await april.nth(0).fill("0");
  await app.getByRole("button", { name: "Home", exact: true }).click();
  await expect(app.getByRole("main", { name: "ホーム", exact: true })).toBeVisible();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "施策入力", exact: true }).click();
  await selectClassification(app.getByRole("spinbutton", { name: "展開名", exact: true }), "コスト");
  await selectClassification(app.getByRole("spinbutton", { name: "業種名", exact: true }), "直営自動車");
  await selectClassification(app.getByRole("spinbutton", { name: "部署名", exact: true }), "部署A");
  await expect(april.nth(0)).toHaveValue("0");
  await expect(april.nth(1)).toHaveValue("-25.5");
  await expect(april.nth(2)).toHaveValue("0");
  await expect(app.getByRole("combobox", { name: /行目の勘定科目/ }).locator("option:checked")).toHaveText(Array(3).fill("501 消耗品費"));
});

test("マスタから科目を管理し、施策で選択して再読込できる", async ({ page, app }, testInfo) => {
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  const master = app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "マスタ", exact: true });
  await master.click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await expect(master).toHaveAttribute("aria-current", "page");
  await expect(app.getByRole("table", { name: "勘定科目一覧" }).getByRole("columnheader")).toHaveText(["順序", "科目コード", "科目名", "科目属性", "操作"]);
  const name = app.getByRole("textbox", { name: "科目名", exact: true });
  const register = app.getByRole("button", { name: "登録", exact: true });
  await name.fill("   ");
  await expect(register).toBeDisabled();
  const code = app.getByRole("textbox", { name: "科目コード", exact: true });
  await expect(code).toHaveAttribute("name", "accountCode");
  await expect(name).toHaveAttribute("name", "accountName");
  await name.fill("売上高");
  await code.fill("12");
  await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
  await register.click();
  await expect(app.getByRole("alert")).toHaveText("科目コードは半角数字3桁で入力してください。");
  await expect(code).toHaveValue("12");
  for (const [code, value] of [["100", "売上高"], ["501", "消耗品費"]] as const) {
    await app.getByRole("textbox", { name: "科目コード", exact: true }).fill(code);
    await name.fill(value);
    await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
    await register.click();
    await expect(app.getByRole("button", { name: `${value}を編集` })).toBeVisible();
  }
  await app.getByRole("textbox", { name: "科目コード", exact: true }).fill("101");
  await name.fill(" 売上高 ");
  await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
  await register.click();
  await expect(app.getByRole("alert")).toHaveText("同じ名前の勘定科目が登録されています。");
  await expect(name).toHaveValue(" 売上高 ");
  await code.fill("100");
  await name.fill("別の科目");
  await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
  await register.click();
  await expect(app.getByRole("alert")).toContainText("同じ科目コードが登録されています。");
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "施策入力", exact: true }).click();
  await selectClassification(app.getByRole("spinbutton", { name: "展開名", exact: true }), "コスト");
  await selectClassification(app.getByRole("spinbutton", { name: "業種名", exact: true }), "直営自動車");
  await selectClassification(app.getByRole("spinbutton", { name: "部署名", exact: true }), "部署A");
  const select = app.getByRole("combobox", { name: "1行目の勘定科目" });
  await expect(select).toHaveValue("");
  await expect(app.getByRole("table", { name: "月別計画金額", exact: true }).getByRole("spinbutton").first()).toBeDisabled();
  await select.selectOption({ label: "100 売上高" });
  await app.getByRole("spinbutton", { name: "売上高 4月の金額", exact: true }).fill("123.5");
  await app.getByRole("button", { name: "＋ 勘定科目を追加", exact: true }).click();
  await expect(app.getByRole("combobox", { name: "2行目の勘定科目" }).locator("option", { hasText: "売上高" })).toBeEnabled();
  await master.click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await expect(app.getByRole("button", { name: "売上高を削除" })).toBeDisabled();
  await app.getByRole("button", { name: "売上高を編集" }).click();
  const editedCode = app.getByRole("textbox", { name: "売上高の科目コード", exact: true });
  const editedName = app.getByRole("textbox", { name: "売上高の科目名", exact: true });
  await expect(editedCode).toBeFocused();
  await expect(app.getByRole("table", { name: "勘定科目一覧" }).getByRole("textbox")).toHaveCount(2);
  await settleMotion(app.locator("body"));
  await attachImage(testInfo, "勘定科目マスタ・表内編集", await page.locator("#app-preview").screenshot());
  await editedName.fill("取り消す変更");
  await app.getByRole("button", { name: "未保存の変更を戻す", exact: true }).click();
  await app.getByRole("button", { name: "完了", exact: true }).click();
  await expect(app.getByRole("button", { name: "売上高を編集" })).toBeFocused();
  await app.getByRole("button", { name: "売上高を編集" }).click();
  await expect(editedName).toHaveValue("売上高");
  await editedCode.fill("501");
  await expect(app.getByRole("alert")).toContainText("同じ科目コードが登録されています。");
  await expect(editedCode).toHaveValue("501");
  await editedCode.fill("001");
  await editedName.fill("売上");
  await app.getByRole("button", { name: "完了", exact: true }).click();
  await expect(app.getByRole("button", { name: "売上を編集" })).toBeVisible();
  await app.getByRole("button", { name: "消耗品費を削除" }).click();
  const confirmation = app.getByRole("alertdialog", { name: "勘定科目を削除" });
  await expect(confirmation).toBeVisible();
  await expect(confirmation).toContainText("「501 消耗品費」を削除しますか？");
  await expect(confirmation.getByRole("button", { name: "キャンセル" })).toBeFocused();
  await app.getByRole("button", { name: "キャンセル", exact: true }).click();
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toBeVisible();
  await app.getByRole("button", { name: "消耗品費を削除" }).click();
  await app.getByRole("button", { name: "削除する", exact: true }).click();
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toHaveCount(0);
  await settleMotion(app.locator("body"));
  expect(await app.locator(".home-content").evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  await attachImage(testInfo, "勘定科目マスタ", await page.locator("#app-preview").screenshot());
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "施策入力", exact: true }).click();
  await selectClassification(app.getByRole("spinbutton", { name: "展開名", exact: true }), "コスト");
  await selectClassification(app.getByRole("spinbutton", { name: "業種名", exact: true }), "直営自動車");
  await selectClassification(app.getByRole("spinbutton", { name: "部署名", exact: true }), "部署A");
  await expect(app.getByRole("spinbutton", { name: "売上 4月の金額", exact: true })).toHaveValue("123.5");
  await expect(select.locator("option:checked")).toHaveText("001 売上");
  await app.getByRole("button", { name: "ファイルを閉じる" }).click();
  await app.getByRole("alertdialog", { name: "ファイルを閉じる", exact: true }).getByRole("button", { name: "閉じる", exact: true }).click();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  await master.click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await expect(app.getByRole("button", { name: "売上を編集" })).toBeVisible();
  await expect(app.locator(".account-code")).toHaveText("001");
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toHaveCount(0);
  await expect(app.getByRole("button", { name: "売上を削除" })).toBeEnabled();
  await app.getByRole("button", { name: "← マスタへ戻る" }).click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
});

test("空のマスタへの案内と、保存に失敗した登録内容を保持する", async ({ page, app }) => {
  await page.getByLabel("ファイル操作", { exact: true }).selectOption("save-failure");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "施策入力", exact: true }).click();
  await selectClassification(app.getByRole("spinbutton", { name: "展開名", exact: true }), "コスト");
  await selectClassification(app.getByRole("spinbutton", { name: "業種名", exact: true }), "直営自動車");
  await selectClassification(app.getByRole("spinbutton", { name: "部署名", exact: true }), "部署A");
  await expect(app.getByRole("combobox", { name: "1行目の勘定科目" })).toBeDisabled();
  await expect(app.getByRole("table", { name: "月別計画金額", exact: true }).getByRole("spinbutton")).toHaveCount(12);
  await app.getByRole("button", { name: "勘定科目マスタを開く" }).click();
  const name = app.getByRole("textbox", { name: "科目名", exact: true });
  await app.getByRole("textbox", { name: "科目コード", exact: true }).fill("100");
  await name.fill("売上高");
  await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await expect(app.getByRole("alert")).toHaveText("テスト用の保存失敗です。");
  await expect(name).toHaveValue("売上高");
  await expect(app.getByRole("table", { name: "勘定科目一覧" }).getByRole("cell")).toHaveText("勘定科目はまだ登録されていません。");
  await expect(app.getByRole("button", { name: "登録", exact: true })).toBeEnabled();
});

test("一覧が長くても削除確認は画面中央に開き、キャンセルで表の位置を保つ", async ({ page, app }, testInfo) => {
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await app.locator(".home-header").getByRole("button", { name: /サイドバー/ }).click();
  for (let index = 1; index <= 25; index++) {
    await app.getByRole("textbox", { name: "科目コード", exact: true }).fill(String(100 + index));
    await app.getByRole("textbox", { name: "科目名", exact: true }).fill(`科目${index}`);
    await app.getByRole("combobox", { name: "科目属性", exact: true }).selectOption("expense");
    await app.getByRole("button", { name: "登録", exact: true }).click();
    await expect(app.getByRole("button", { name: `科目${index}を削除`, exact: true })).toBeVisible();
  }
  await app.getByRole("button", { name: "通知を閉じる" }).click();
  const trigger = app.getByRole("button", { name: "科目25を削除", exact: true });
  await trigger.scrollIntoViewIfNeeded();
  await settleMotion(app.locator("body"));
  const readPosition = (node: HTMLElement) => ({ scroll: node.scrollTop, table: node.querySelector("table")!.getBoundingClientRect().toJSON() });
  const before = await app.locator(".account-master-list").evaluate(readPosition);
  expect(before.scroll).toBeGreaterThan(0);
  await trigger.click();
  const dialog = app.getByRole("alertdialog", { name: "勘定科目を削除" });
  await expect(dialog).toBeVisible();
  await expect(dialog).toContainText("「125 科目25」を削除しますか？");
  await settleMotion(app.locator("body"));
  expect(await app.locator(".account-master-list").evaluate(readPosition)).toEqual(before);
  const placement = await dialog.evaluate(node => {
    const { x, y, width, height } = node.getBoundingClientRect();
    return { x, y, width, height, viewportWidth: window.innerWidth, viewportHeight: window.innerHeight, modal: node.matches(":modal") };
  });
  expect(placement.modal).toBe(true);
  expect(Math.abs(placement.x + placement.width / 2 - placement.viewportWidth / 2)).toBeLessThan(1);
  expect(Math.abs(placement.y + placement.height / 2 - placement.viewportHeight / 2)).toBeLessThan(1);
  expect(placement.y).toBeGreaterThanOrEqual(16);
  expect(placement.x).toBeGreaterThanOrEqual(16);
  const cancel = dialog.getByRole("button", { name: "キャンセル", exact: true });
  const confirm = dialog.getByRole("button", { name: "削除する", exact: true });
  await expect(cancel).toBeFocused();
  await cancel.press("Tab");
  await expect(confirm).toBeFocused();
  await confirm.press("Tab");
  await expect(cancel).toBeFocused();
  await attachImage(testInfo, "削除確認ダイアログ", await page.locator("#app-preview").screenshot());
  await cancel.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  expect(await app.locator(".account-master-list").evaluate(readPosition)).toEqual(before);
  await expect(app.getByRole("table").getByRole("row")).toHaveCount(26);
});
