import { test, expect, settleMotion, attachImage } from "./fixtures";

test("マスタから科目を管理し、施策で選択して再読込できる", async ({ page, app }, testInfo) => {
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  const master = app.getByRole("button", { name: "マスタ", exact: true });
  await master.click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await expect(master).toHaveAttribute("aria-current", "page");
  const name = app.getByRole("textbox", { name: "科目名", exact: true });
  const register = app.getByRole("button", { name: "登録", exact: true });
  await name.fill("   ");
  await expect(register).toBeDisabled();
  const code = app.getByRole("textbox", { name: "科目コード", exact: true });
  await expect(code).toHaveAttribute("name", "accountCode");
  await expect(name).toHaveAttribute("name", "accountName");
  await name.fill("売上高");
  await code.fill("12");
  await register.click();
  await expect(app.getByRole("alert")).toHaveText("科目コードは半角数字3桁で入力してください。");
  await expect(code).toHaveValue("12");
  for (const [code, value] of [["100", "売上高"], ["501", "消耗品費"]] as const) {
    await app.getByRole("textbox", { name: "科目コード", exact: true }).fill(code);
    await name.fill(value);
    await register.click();
    await expect(app.getByRole("button", { name: `${value}を編集` })).toBeVisible();
  }
  await app.getByRole("textbox", { name: "科目コード", exact: true }).fill("101");
  await name.fill(" 売上高 ");
  await register.click();
  await expect(app.getByRole("alert")).toHaveText("同じ名前の勘定科目が登録されています。");
  await expect(name).toHaveValue(" 売上高 ");
  await code.fill("100");
  await name.fill("別の科目");
  await register.click();
  await expect(app.getByRole("alert")).toHaveText("同じ科目コードが登録されています。");
  await app.getByRole("button", { name: "施策入力", exact: true }).click();
  const select = app.getByRole("combobox", { name: "1行目の勘定科目" });
  await expect(select).toHaveValue("");
  await expect(app.getByRole("spinbutton").first()).toBeDisabled();
  await select.selectOption({ label: "100 売上高" });
  await app.getByRole("spinbutton", { name: "売上高 4月の金額", exact: true }).fill("123.5");
  await app.getByRole("button", { name: "＋ 勘定科目を追加", exact: true }).click();
  await expect(app.getByRole("combobox", { name: "2行目の勘定科目" }).locator("option", { hasText: "売上高" })).toBeDisabled();
  await master.click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await expect(app.getByRole("button", { name: "売上高を削除" })).toBeDisabled();
  await app.getByRole("button", { name: "売上高を編集" }).click();
  await code.fill("001");
  await name.fill("売上");
  await app.getByRole("button", { name: "変更を保存" }).click();
  await expect(app.getByRole("button", { name: "売上を編集" })).toBeVisible();
  await app.getByRole("button", { name: "消耗品費を削除" }).click();
  await app.getByRole("button", { name: "キャンセル", exact: true }).click();
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toBeVisible();
  await app.getByRole("button", { name: "消耗品費を削除" }).click();
  await app.getByRole("button", { name: "削除する", exact: true }).click();
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toHaveCount(0);
  await settleMotion(app.locator("body"));
  expect(await app.locator(".home-content").evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  await attachImage(testInfo, "勘定科目マスタ", await page.locator("#app-preview").screenshot());
  await app.getByRole("button", { name: "施策入力", exact: true }).click();
  await expect(app.getByRole("spinbutton", { name: "売上 4月の金額", exact: true })).toHaveValue("123.5");
  await expect(select.locator("option:checked")).toHaveText("001 売上");
  await app.getByRole("button", { name: "ファイルを閉じる" }).click();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  await master.click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await expect(app.getByRole("button", { name: "売上を編集" })).toBeVisible();
  await expect(app.locator(".account-code")).toHaveText("001");
  await expect(app.getByRole("button", { name: "消耗品費を編集" })).toHaveCount(0);
  await expect(app.getByRole("button", { name: "売上を削除" })).toBeEnabled();
  await app.getByRole("button", { name: "← マスタへ戻る" }).click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
});

test("空のマスタへの案内と、保存に失敗した登録内容を保持する", async ({ page, app }) => {
  await page.getByLabel("ファイル操作", { exact: true }).selectOption("save-failure");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く" }).click();
  await app.getByRole("button", { name: "施策入力", exact: true }).click();
  await expect(app.getByRole("combobox", { name: "1行目の勘定科目" })).toBeDisabled();
  await expect(app.getByRole("spinbutton")).toHaveCount(12);
  await app.getByRole("button", { name: "勘定科目マスタを開く" }).click();
  const name = app.getByRole("textbox", { name: "科目名", exact: true });
  await app.getByRole("textbox", { name: "科目コード", exact: true }).fill("100");
  await name.fill("売上高");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await expect(app.getByRole("alert")).toHaveText("テスト用の保存失敗です。");
  await expect(name).toHaveValue("売上高");
  await expect(app.getByRole("heading", { name: "登録済みの勘定科目 0件" })).toBeVisible();
  await expect(app.getByRole("button", { name: "登録", exact: true })).toBeEnabled();
});
