import { openInitiativeEntry, test, expect, settleMotion } from "./fixtures";

test("施策名・備考の右側のスロットで分類を選択し、登録後も保持する", async ({ page, app }) => {
  await page.getByLabel("テストデータ", { exact: true }).selectOption("defaults");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await openInitiativeEntry(app);
  await app.getByRole("heading", { name: "施策入力", exact: true }).click();
  await settleMotion(app.locator("body"));
  const name = app.getByRole("textbox", { name: "施策名", exact: true });
  const register = app.getByRole("button", { name: "登録", exact: true });
  await name.fill("分類スロット確認");
  await expect(register).toBeDisabled();
  const expansion = app.getByRole("spinbutton", { name: "展開名", exact: true });
  await expect(expansion).toHaveAttribute("aria-valuetext", "未選択");
  await app.getByRole("button", { name: "展開名の次の候補", exact: true }).click();
  await expect(expansion).toHaveAttribute("aria-valuetext", "コスト");
  await expansion.press("ArrowDown");
  await expect(expansion).toHaveAttribute("aria-valuetext", "料改");
  await expansion.press("Home");
  await expect(expansion).toHaveAttribute("aria-valuetext", "未選択");
  await expansion.click();
  await expansion.press("Space");
  await expansion.press("Enter");
  await expect(expansion).toHaveAttribute("aria-valuetext", "未選択");
  await expect(app.locator(".classification-slot select")).toHaveCount(0);
  const slot = app.locator(".classification-slot").first();
  await slot.hover();
  await page.mouse.wheel(0, 24);
  await expect(expansion).toHaveAttribute("aria-valuetext", "コスト");
  const rect = (await slot.boundingBox())!;
  expect(rect.height).toBe(72);
  await page.mouse.move(rect.x + rect.width / 2, rect.y + 60);
  await page.mouse.down();
  await page.mouse.move(rect.x + rect.width / 2, rect.y + 36, { steps: 6 });
  await page.mouse.up();
  await expect(expansion).toHaveAttribute("aria-valuetext", "料改");
  await settleMotion(slot);
  const selected = (await slot.locator(".is-selected").boundingBox())!;
  expect(Math.abs(selected.y + selected.height / 2 - rect.y - rect.height / 2)).toBeLessThanOrEqual(1);
  await app.getByRole("button", { name: "部署名の次の候補", exact: true }).click();
  await app.getByRole("button", { name: "業種名の次の候補", exact: true }).click();
  await expect(app.getByRole("spinbutton", { name: "期間名", exact: true })).toHaveAttribute("aria-valuetext", "未選択");
  await expect(register).toBeEnabled();
  for (const width of [1280, 375]) {
    await page.setViewportSize({ width, height: 864 });
    await settleMotion(app.locator("body"));
    const text = (await app.locator(".initiative-text-fields").boundingBox())!;
    const slots = (await app.locator(".initiative-classification-slots").boundingBox())!;
    if (width === 1280) {
      expect(slots.x).toBeGreaterThanOrEqual(text.x + text.width);
      expect(slots.width).toBeLessThanOrEqual(440);
    }
    else expect(slots.y).toBeGreaterThanOrEqual(text.y + text.height);
    expect(await app.locator("html").evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  }
  await app.getByRole("combobox", { name: "1行目の勘定科目" }).selectOption("1");
  await register.click();
  await expect(app.getByRole("heading", { name: "施策一覧", exact: true })).toBeVisible();
  await app.getByRole("button", { name: "分類スロット確認", exact: true }).click();
  await expect(expansion).toHaveAttribute("aria-valuetext", "料改");
  await expect(app.getByRole("spinbutton", { name: "部署名", exact: true })).toHaveAttribute("aria-valuetext", "部署A");
  await expect(app.getByRole("spinbutton", { name: "業種名", exact: true })).toHaveAttribute("aria-valuetext", "直営自動車");
  await expect(app.getByRole("spinbutton", { name: "期間名", exact: true })).toHaveAttribute("aria-valuetext", "未選択");
});

test("スロットの外で離した後と取消後の移動で分類を変更しない", async ({ page, app }) => {
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await openInitiativeEntry(app);
  const slot = app.getByRole("spinbutton", { name: "展開名", exact: true });
  await settleMotion(app.locator("body"));
  const rect = (await slot.boundingBox())!;
  const x = rect.x + rect.width / 2, y = rect.y + rect.height / 2;
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.move(rect.x - 20, y + 3);
  await page.mouse.up();
  await page.mouse.move(x, y);
  await page.mouse.move(x, y - 24);
  await expect(slot).toHaveAttribute("aria-valuetext", "未選択");
  await page.mouse.move(x, y);
  await page.mouse.down();
  await slot.dispatchEvent("pointercancel", { pointerId: 1, pointerType: "mouse" });
  await slot.dispatchEvent("pointermove", { pointerId: 1, pointerType: "mouse", clientY: y - 24 });
  await expect(slot).toHaveAttribute("aria-valuetext", "未選択");
  await page.mouse.up();
  await app.getByRole("button", { name: "展開名の次の候補", exact: true }).click();
  await expect(slot).toHaveAttribute("aria-valuetext", "コスト");
  await slot.press("Home");
  await expect(slot).toHaveAttribute("aria-valuetext", "未選択");
});
