import { test, expect, settleMotion, attachImage } from "./fixtures";

test("明細の直接編集・フィルター・ソート・施策への移動と帰還", async ({ page, app }, testInfo) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "明細", exact: true }).click();
  const table = app.locator(".detail-table");
  await expect(table.locator("tbody tr")).toHaveCount(396);
  await settleMotion(app.locator("body"));
  const first = table.locator("tbody tr").first();
  const id = await first.getAttribute("data-detail-id");
  const amount = app.locator(`[data-cell="${id}-amount"]`);
  await amount.dblclick();
  await app.getByLabel("金額を編集", { exact: true }).fill("12.345");
  await app.getByLabel("金額を編集", { exact: true }).press("Tab");
  await expect(amount).toHaveText("12.345");
  await expect(app.locator(`[data-cell="${id}-note"]`)).toBeFocused();
  await table.getByRole("button", { name: "施策名のフィルター", exact: true }).click();
  await app.getByRole("checkbox", { name: "すべて", exact: true }).uncheck();
  await app.getByRole("checkbox", { name: "前年度の販売施策", exact: true }).check();
  await app.getByRole("button", { name: "閉じる", exact: true }).click();
  await expect(table.locator("tbody tr")).toHaveCount(24);
  await table.getByRole("button", { name: "金額で昇順に並べ替え", exact: true }).click();
  await table.getByRole("button", { name: "金額で降順に並べ替え", exact: true }).click();
  const link = table.getByRole("button", { name: "前年度の販売施策", exact: true }).first();
  await link.dblclick();
  await expect(app.getByLabel("施策名を編集", { exact: true })).toBeVisible();
  await app.getByLabel("施策名を編集", { exact: true }).press("Escape");
  await link.click();
  await app.getByRole("button", { name: "← 明細へ戻る", exact: true }).click();
  await expect(table.locator("tbody tr")).toHaveCount(24);
  await expect(table.getByRole("button", { name: "金額で昇順に並べ替え", exact: true })).toHaveText("金額 ↓");
  await app.getByRole("button", { name: "クリア", exact: true }).click();
  await expect(table.locator("tbody tr")).toHaveCount(396);
  await expect(table.locator("tbody tr").first()).toHaveAttribute("data-detail-id", id!);
  const region = app.locator(".detail-scroll");
  expect(await region.evaluate(node => node.scrollWidth > node.clientWidth)).toBe(true);
  expect(await app.locator(".home-content").evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  await settleMotion(app.locator("body"));
  await attachImage(testInfo, "明細", await page.locator("#app-preview").screenshot());
});

test("不正値と保存失敗で入力を保持し、取消では元の値に戻る", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await page.getByLabel("ファイル操作").selectOption("save-failure");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "明細", exact: true }).click();
  const cell = app.locator(".detail-table tbody tr").first().locator("td").nth(9);
  const original = await cell.innerText();
  await cell.dblclick();
  const input = app.getByLabel("金額を編集", { exact: true });
  await input.fill("0.0001"); await input.press("Enter");
  await expect(app.getByRole("alert")).toContainText("3桁");
  await expect(input).toHaveValue("0.0001");
  await input.fill("15"); await input.press("Enter");
  await expect(app.getByRole("alert")).toContainText("保存失敗");
  await expect(input).toHaveValue("15");
  await expect(app.getByRole("button", { name: "施策一覧", exact: true })).toBeDisabled();
  await input.press("Escape"); await expect(cell).toHaveText(original);
});
