import { openInitiativeEntry, test, expect, selectClassification, settleMotion, attachImage } from "./fixtures";

test("展開名ごとの集計・並び順・編集からの移動と再読込を確認する", async ({ page, app }, testInfo) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "展開表", exact: true }).click();
  const table = app.getByRole("table", { name: "展開表", exact: true });
  await expect(table).toBeVisible();
  await expect(table.getByRole("row").filter({ has: app.getByRole("rowheader", { name: "前年", exact: true }) }).getByRole("cell").first()).toHaveText("20,342");
  await expect(table.getByRole("row").filter({ has: app.getByRole("rowheader", { name: "合計", exact: true }) }).getByRole("cell").first()).toHaveText("20,757");
  await expect(table.getByRole("row").filter({ has: app.getByRole("rowheader", { name: "展開計", exact: true }) }).getByRole("cell").first()).toHaveText("415");
  await expect(table.getByRole("row").filter({ has: app.getByRole("rowheader", { name: "撤退計", exact: true }) }).getByRole("cell").first()).toHaveText("");
  await expect(table.locator("thead tr").first().locator("th").first()).toHaveText("展開名");
  await expect(table.locator("thead tr").first().locator("th").nth(1)).toHaveText("期間名");
  await expect(table.locator("thead tr").first().locator("th").nth(2)).toHaveText("施策名");
  const salesGroup = table.locator("tbody").filter({ has: app.locator(".expansion-group").filter({ hasText: /^拡販$/ }) });
  await expect(salesGroup.locator(".expansion-period")).toHaveText(["期間差", "新規"]);
  await expect(salesGroup.locator(".expansion-period").nth(1)).toHaveAttribute("rowspan", "7");
  const registeredOrder = await table.getByRole("button").allTextContents();
  await expect(table.locator("thead button")).toHaveCount(0);
  await expect(app.getByRole("button", { name: "クリア", exact: true })).toHaveCount(0);
  await table.getByRole("button", { name: "既存商品の販売拡大", exact: true }).click();
  await expect(app.getByRole("spinbutton", { name: "展開名", exact: true })).toHaveAttribute("aria-valuetext", "拡販");
  await selectClassification(app.getByRole("spinbutton", { name: "展開名", exact: true }), "効率");
  await expect(app.getByRole("button", { name: "← 展開表へ戻る", exact: true })).toBeEnabled();
  await app.getByRole("button", { name: "← 展開表へ戻る", exact: true }).click();
  const movedGroup = table.locator("tbody").filter({ has: app.getByRole("rowheader", { name: "効率", exact: true }) });
  await expect(movedGroup.getByRole("button", { name: "既存商品の販売拡大", exact: true })).toBeVisible();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^展開マスタ/ }).click();
  await expect(app.getByRole("button", { name: "効率を削除", exact: true })).toBeDisabled();
  await expect(app.getByRole("button", { name: "撤退を削除", exact: true })).toBeEnabled();
  await app.getByRole("button", { name: "ファイルを閉じる", exact: true }).click();
  await app.getByRole("alertdialog", { name: "ファイルを閉じる", exact: true }).getByRole("button", { name: "閉じる", exact: true }).click();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("complementary", { name: "メニュー" }).getByRole("button", { name: "展開表", exact: true }).click();
  await expect(movedGroup.getByRole("button", { name: "既存商品の販売拡大", exact: true })).toBeVisible();
  expect(await table.getByRole("button").allTextContents()).toHaveLength(registeredOrder.length);
  await settleMotion(app.locator("body"));
  const region = app.getByRole("region", { name: "展開表の月別種別・比較", exact: true });
  expect(await region.evaluate(node => node.scrollWidth > node.clientWidth)).toBe(true);
  await table.getByRole("row").filter({ has: app.getByRole("rowheader", { name: "前年", exact: true }) }).getByRole("cell").last().scrollIntoViewIfNeeded();
  await region.evaluate(node => { node.scrollLeft = node.scrollWidth; });
  await expect(table.getByRole("row").filter({ has: app.getByRole("rowheader", { name: "前年", exact: true }) }).getByRole("cell").last()).toBeInViewport();
  await region.evaluate(node => { node.scrollLeft = 0; });
  await attachImage(testInfo, "展開表", await page.locator("#app-preview").screenshot());
});

test("新規施策の展開名を必須にして保存し、失敗した変更を保持する", async ({ app }) => {
  await app.locator("body").evaluate(() => {
    const target = window as Window & { showSaveFilePicker?: (options: { suggestedName: string }) => Promise<FileSystemFileHandle> };
    const original = target.showSaveFilePicker!;
    let writes = 0;
    Object.defineProperty(target, "showSaveFilePicker", { value: async (options: { suggestedName: string }) => {
      const handle = await original(options);
      const create = handle.createWritable.bind(handle);
      Object.defineProperty(handle, "createWritable", { value: async () => {
        if (++writes === 3) throw new Error("展開名変更の保存失敗");
        return create();
      } });
      return handle;
    } });
  });
  await app.getByRole("button", { name: "新規作成", exact: true }).click();
  await openInitiativeEntry(app);
  const expansion = app.getByRole("spinbutton", { name: "展開名", exact: true });
  await expect(expansion).toHaveAttribute("aria-valuetext", "未選択");
  await app.getByRole("textbox", { name: "施策名", exact: true }).fill("展開割り当て確認");
  await expect(app.getByRole("button", { name: "登録", exact: true })).toBeDisabled();
  await selectClassification(expansion, "料改");
  await selectClassification(app.getByRole("spinbutton", { name: "業種名", exact: true }), "直営自動車");
  await selectClassification(app.getByRole("spinbutton", { name: "部署名", exact: true }), "部署A");
  await app.getByRole("combobox", { name: "1行目の勘定科目", exact: true }).selectOption({ label: "401 売上高" });
  await app.getByRole("spinbutton", { name: "売上高 4月の金額", exact: true }).fill("123.456");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await app.getByRole("button", { name: "展開割り当て確認", exact: true }).click();
  await expect(expansion).toHaveAttribute("aria-valuetext", "料改");
  await selectClassification(expansion, "効率");
  await expect(app.getByRole("alert")).toBeVisible();
  await expect(expansion).toHaveAttribute("aria-valuetext", "効率");
  await expect(app.getByRole("button", { name: "← 施策一覧へ戻る", exact: true })).toBeDisabled();
  await app.getByRole("button", { name: "入力を取り消す", exact: true }).click();
  await expect(expansion).toHaveAttribute("aria-valuetext", "料改");
});
