import { openInitiativeEntry, test, expect } from "./fixtures";

test("展開区分を展開で絞り、共通区分を保持し、未選択でも登録できる", async ({ page, app }) => {
  await page.getByLabel("テストデータ", { exact: true }).selectOption("full");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await openInitiativeEntry(app);
  const expansion = app.getByRole("combobox", { name: "展開名", exact: true });
  const category = app.getByRole("combobox", { name: "展開区分", exact: true });
  await expect(category).toBeDisabled();
  await expansion.selectOption("1");
  await expect(category.locator("option")).toHaveText(["未選択", "確認用：契約見直し", "確認用：作業改善", "確認用：共通区分"]);
  await category.selectOption("3");
  await expansion.selectOption("2");
  await expect(category).toHaveValue("3");
  await expect(category).toBeEnabled();
  await category.selectOption("");
  await expect(category).toHaveValue("");
  await expansion.selectOption("1"); await category.selectOption("1");
  await expansion.selectOption("2"); await expect(category).toHaveValue("");
  await expansion.selectOption("3"); await expect(category).toBeDisabled();
  await expansion.selectOption("2");
  await app.getByRole("combobox", { name: "部署名", exact: true }).selectOption("1");
  await app.getByRole("combobox", { name: "業種名", exact: true }).selectOption("1");
  await app.getByRole("textbox", { name: "施策名", exact: true }).fill("展開区分の確認");
  const account = app.getByRole("combobox", { name: "1行目の勘定科目" }); await account.focus(); await account.selectOption("1");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await app.getByRole("button", { name: "展開区分の確認", exact: true }).click();
  await expect(category).toHaveValue("");
  await category.selectOption("3");
  const back = app.getByRole("button", { name: "← 施策一覧へ戻る", exact: true }); await expect(back).toBeEnabled(); await back.click();
  await app.getByRole("button", { name: "展開区分の確認", exact: true }).click();
  await expect(category).toHaveValue("3");
});

test("空の展開区分マスタに登録し、展開へ割り当てる", async ({ page, app }) => {
  await page.getByLabel("テストデータ", { exact: true }).selectOption("defaults");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^展開区分マスタ/ }).click();
  await expect(app.getByText("展開区分はまだ登録されていません。", { exact: true })).toBeVisible();
  await app.getByRole("textbox", { name: "展開区分名", exact: true }).fill("追加区分");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await expect(app.getByRole("button", { name: "追加区分を編集", exact: true })).toBeEnabled();
  await app.getByRole("button", { name: "← マスタへ戻る", exact: true }).click();
  await app.getByRole("button", { name: /^展開マスタ/ }).click();
  await app.getByRole("button", { name: "コストを編集", exact: true }).click();
  await app.getByRole("group", { name: "コストの展開区分", exact: true }).getByRole("checkbox", { name: "追加区分", exact: true }).check();
  await expect(app.getByRole("button", { name: "完了", exact: true })).toBeEnabled();
  await app.getByRole("button", { name: "完了", exact: true }).click();
  await openInitiativeEntry(app);
  await app.getByRole("combobox", { name: "展開名", exact: true }).selectOption("1");
  const category = app.getByRole("combobox", { name: "展開区分", exact: true });
  await expect(category).toHaveValue("");
  await expect(category.locator("option")).toHaveText(["未選択", "追加区分"]);
  await category.selectOption({ label: "追加区分" });
  await expect(category.locator("option:checked")).toHaveText("追加区分");
});
