import { test, expect } from '@playwright/test';

test('確定予算の施策内超過でも編集・保存・取消・再読込・履歴閲覧を維持', async ({ page }) => {
  const unexpected: string[] = [];
  page.on('pageerror', error => unexpected.push(error.message));
  await page.goto('/tests/ui/preview.html?data=overflow-initiative');
  await expect(page.getByRole('status')).toHaveText('操作できます');
  const app = page.frameLocator('#app-preview');
  await app.getByRole('button', { name: 'ファイルを開く', exact: true }).click();
  const nav = app.getByRole('navigation', { name: 'メインナビゲーション' });
  await expect(app.getByRole('main', { name: 'ホーム', exact: true })).toBeVisible();
  await nav.getByRole('button', { name: '施策一覧', exact: true }).click();
  const alert = app.getByRole('alert');
  await expect(alert).toContainText('範囲を超えています');
  const normal = app.getByRole('row').filter({ has: app.getByRole('button', { name: '通常確認', exact: true }) });
  await expect(normal.getByRole('cell').nth(3)).toHaveText('2');
  const kind = app.getByRole('spinbutton', { name: '種別', exact: true });
  await kind.getByRole('button', { name: '一次予算', exact: true }).click();
  await expect(alert).toHaveCount(0);
  await expect(nav.getByRole('button', { name: 'Home', exact: true })).toBeEnabled();
  await kind.getByRole('button', { name: '確定予算', exact: true }).click();
  await expect(alert).toContainText('範囲を超えています');
  await app.getByRole('button', { name: '上限確認A', exact: true }).click();
  await app.getByRole('tab', { name: '確定予算', exact: true }).click();
  const april = app.getByRole('spinbutton', { name: '売上高 4月の金額', exact: true }).first();
  await expect(april).toHaveValue('5000000000000');
  await april.fill('1'); await april.press('Tab');
  await expect(nav.getByRole('button', { name: '施策一覧', exact: true })).toBeEnabled();
  await app.getByRole('button', { name: '操作を取り消す', exact: true }).click();
  await expect(april).toHaveValue('5000000000000');
  await app.getByRole('button', { name: '← 施策一覧へ戻る', exact: true }).click();
  await expect(alert).toContainText('範囲を超えています');
  await app.getByRole('button', { name: '操作をやり直す', exact: true }).click();
  await expect(alert).toHaveCount(0);
  // Create the same overflow through a real edit/save, rather than just loading a fixture.
  await app.getByRole('button', { name: '上限確認A', exact: true }).click();
  await app.getByRole('tab', { name: '確定予算', exact: true }).click();
  await april.fill('5000000000000'); await april.press('Tab');
  await expect(nav.getByRole('button', { name: 'Home', exact: true })).toBeEnabled();
  await nav.getByRole('button', { name: 'Home', exact: true }).click();
  await expect(app.getByRole('main', { name: 'ホーム', exact: true })).toBeVisible();
  await app.getByRole('button', { name: 'ファイルを閉じる', exact: true }).click();
  await app.getByRole('alertdialog').getByRole('button', { name: '閉じる', exact: true }).click();
  await app.getByRole('button', { name: 'ファイルを開く', exact: true }).click();
  await expect(app.getByRole('main', { name: 'ホーム', exact: true })).toBeVisible();
  await nav.getByRole('button', { name: '施策一覧', exact: true }).click();
  await expect(alert).toContainText('範囲を超えています');
  await nav.getByRole('button', { name: '履歴', exact: true }).click();
  await app.locator('.history-date').first().click();
  await expect(app.getByLabel('過去のデータを閲覧中')).toBeVisible();
  await nav.getByRole('button', { name: '施策一覧', exact: true }).click();
  await expect(alert).toContainText('範囲を超えています');
  await app.getByRole('button', { name: '上限確認A', exact: true }).click();
  await app.getByRole('tab', { name: '確定予算', exact: true }).click();
  await expect(april).toHaveValue('5000000000000');
  await expect(april).toBeDisabled();
  await app.getByRole('button', { name: '現在に戻る', exact: true }).click();
  await expect(app.getByRole('heading', { name: '履歴', exact: true })).toBeVisible();
  await nav.getByRole('button', { name: '施策一覧', exact: true }).click();
  await expect(alert).toContainText('範囲を超えています');
  await app.getByRole('button', { name: '上限確認A', exact: true }).click();
  await app.getByRole('tab', { name: '確定予算', exact: true }).click();
  await expect(april).toBeEnabled();
  await expect(app.locator('vite-error-overlay')).toHaveCount(0);
  expect(unexpected).toEqual([]);
});
