import {test, expect} from './fixtures';

test('巨大計画でも全件を保持し、描画・並べ替え・編集を画面範囲に限定する', async ({page,app}) => {
  test.setTimeout(120_000);
  await page.getByLabel('テストデータ').selectOption('large');
  await expect(page.getByRole('status')).toHaveText('操作できます');
  await app.getByRole('button',{name:'ファイルを開く',exact:true}).click();
  const nav=app.getByRole('navigation',{name:'メインナビゲーション'});
  await expect(nav).toBeAttached();
  const navigate=async(name:string)=>{
    await app.getByRole('button',{name:'サイドバーを開く',exact:true}).click();
    await nav.getByRole('button',{name,exact:true}).click();
    await app.getByRole('button',{name:'サイドバーを閉じる',exact:true}).last().click();
    await expect(app.getByRole('heading',{name,exact:true})).toBeVisible();
  };
  await navigate('施策一覧');
  const list=app.locator('.initiative-list-table');
  await expect(list).toHaveAttribute('aria-rowcount','1017');
  expect(await list.locator('tbody tr:not(.virtual-row-spacer)').count()).toBeLessThan(60);
  const total=await list.locator('tfoot').textContent();
  await app.locator('.initiative-list-container').evaluate(el=>{el.scrollTop=el.scrollHeight;});
  await expect(list.getByRole('button',{name:'大規模確認施策1000',exact:true})).toBeAttached();
  expect(await list.locator('tbody tr:not(.virtual-row-spacer)').count()).toBeLessThan(60);
  expect(await list.locator('tfoot').textContent()).toBe(total);
  await navigate('展開表');
  const expansion=app.locator('.expansion-table-page .initiative-list-table');
  expect(await expansion.locator('tbody tr:not(.virtual-row-spacer)').count()).toBeLessThan(60);
  await app.locator('.expansion-table-page .initiative-list-container').evaluate(el=>{el.scrollTop=el.scrollHeight;});
  await expect(expansion.locator('.expansion-subtotal-name').last()).toContainText('計');
  await expect(nav.getByRole('button',{name:'明細',exact:true})).toHaveCount(0);
  await navigate('施策一覧');
  await app.locator('.initiative-list-container').evaluate(el=>{el.scrollTop=0;});
  await list.getByRole('button',{name:'既存商品の販売拡大',exact:true}).click();
  await app.getByRole('tab',{name:'一次予算',exact:true}).click();
  const amount=app.getByRole('spinbutton',{name:'売上高 4月の金額',exact:true}).first();
  await expect(amount).toHaveValue('120');
  await amount.fill('130');
  await amount.press('Tab');
  await expect(app.getByRole('button',{name:'操作を取り消す',exact:true})).toBeEnabled({timeout:60_000});
  await app.getByRole('button',{name:'操作を取り消す',exact:true}).click();
  await expect(amount).toHaveValue('120',{timeout:60_000});
  await expect(app.getByRole('button',{name:'操作をやり直す',exact:true})).toBeEnabled();
});
