import { test, expect, selectClassification, settleMotion } from "./fixtures";

test("保存済み施策の編集・登録を取り消してやり直し、新しい保存と再開で履歴を整理する", async ({ page, app }, testInfo) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  const undo = app.getByRole("button", { name: "操作を取り消す", exact: true });
  const redo = app.getByRole("button", { name: "操作をやり直す", exact: true });
  await expect(undo).toBeDisabled();
  await expect(redo).toBeDisabled();
  const menu = app.getByRole("navigation", { name: "メインナビゲーション" });
  await menu.getByRole("button", { name: "施策一覧", exact: true }).click();
  await app.getByRole("button", { name: "既存商品の販売拡大", exact: true }).click();
  const amount = app.getByRole("spinbutton", { name: "売上高 4月の金額", exact: true }).first();
  await amount.fill("130.001");
  await expect(undo).toBeDisabled();
  await expect(undo).toBeEnabled();
  await undo.click();
  await expect(amount).toHaveValue("120");
  await expect(redo).toBeEnabled();
  await redo.click();
  await expect(amount).toHaveValue("130.001");
  await app.getByRole("tab", { name: "確定予算", exact: true }).click();
  await expect(amount).toHaveValue("130");
  await app.getByRole("tab", { name: "一次予算", exact: true }).click();
  await undo.click();
  await expect(amount).toHaveValue("120");
  await amount.fill("140");
  await expect(undo).toBeEnabled();
  await expect(redo).toBeDisabled();
  await undo.click();
  await expect(amount).toHaveValue("120");
  await redo.click();
  await expect(amount).toHaveValue("140");
  await app.getByRole("button", { name: "← 施策一覧へ戻る", exact: true }).click();
  await app.getByRole("button", { name: "施策を追加", exact: true }).click();
  await app.getByRole("textbox", { name: "施策名", exact: true }).fill("取消確認施策");
  await expect(undo).toBeDisabled();
  await selectClassification(app.getByRole("combobox", { name: "展開名", exact: true }), "コスト");
  await selectClassification(app.getByRole("combobox", { name: "部署名", exact: true }), "部署A");
  await selectClassification(app.getByRole("combobox", { name: "業種名", exact: true }), "直営自動車");
  await app.getByRole("combobox", { name: "1行目の勘定科目", exact: true }).focus();
  await app.getByRole("combobox", { name: "1行目の勘定科目", exact: true }).selectOption({ label: "401 売上高" });
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await app.getByRole("button", { name: "取消確認施策", exact: true }).click();
  await undo.click();
  await expect(app.getByRole("heading", { name: "施策一覧", exact: true })).toBeVisible();
  await expect(app.getByRole("button", { name: "取消確認施策", exact: true })).toHaveCount(0);
  await app.getByRole("button", { name: "前の画面に戻る", exact: true }).click();
  await expect(app.getByRole("heading", { name: "施策入力", exact: true })).toBeVisible();
  await app.getByRole("button", { name: "次の画面に進む", exact: true }).click();
  await expect(app.getByRole("heading", { name: "施策一覧", exact: true })).toBeVisible();
  await redo.click();
  await expect(app.getByRole("button", { name: "取消確認施策", exact: true })).toBeVisible();
  await settleMotion(app.locator("body"));
  await page.screenshot({ path: `/tmp/triadichrome-saved-operations-${testInfo.project.name}.png` });
  await app.getByRole("button", { name: "ファイルを閉じる", exact: true }).click();
  await app.getByRole("alertdialog").getByRole("button", { name: "閉じる", exact: true }).click();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await expect(undo).toBeDisabled();
  await expect(redo).toBeDisabled();
  await menu.getByRole("button", { name: "施策一覧", exact: true }).click();
  await expect(app.getByRole("button", { name: "取消確認施策", exact: true })).toBeVisible();
});

test("マスタの編集・削除、保存失敗の再試行、ダイアログと文字入力の保護", async ({ app }) => {
  await app.locator("body").evaluate(() => {
    const target = window as Window & { showOpenFilePicker?: () => Promise<FileSystemFileHandle[]> };
    const original = target.showOpenFilePicker!;
    Object.defineProperty(target, "showOpenFilePicker", { value: async () => {
      const handles = await original();
      const handle = handles[0]!;
      const create = handle.createWritable.bind(handle);
      let writes = 0;
      Object.defineProperty(handle, "createWritable", { value: async () => {
        if (++writes === 3) throw new Error("取り消しの保存失敗");
        return create();
      } });
      return handles;
    } });
  });
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  const undo = app.getByRole("button", { name: "操作を取り消す", exact: true });
  const redo = app.getByRole("button", { name: "操作をやり直す", exact: true });
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^部署マスタ/ }).click();
  const newName = app.getByRole("textbox", { name: "部署名", exact: true });
  await newName.fill("操作用部署");
  await app.getByRole("form", { name: "部署の新規登録", exact: true }).getByRole("checkbox", { name: "直営自動車", exact: true }).check();
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await app.getByRole("button", { name: "操作用部署を編集", exact: true }).click();
  await app.getByRole("textbox", { name: "操作用部署の部署名", exact: true }).fill("更新済み部署");
  await expect(app.getByRole("button", { name: "完了", exact: true })).toBeEnabled();
  await undo.click();
  await expect(app.getByRole("alert")).toContainText("取り消しの保存失敗");
  await expect(app.getByRole("textbox", { name: "更新済み部署の部署名", exact: true })).toHaveValue("更新済み部署");
  await expect(redo).toBeDisabled();
  await undo.click();
  await expect(app.getByRole("button", { name: "操作用部署を編集", exact: true })).toBeVisible();
  await redo.click();
  await app.getByRole("button", { name: "更新済み部署を削除", exact: true }).click();
  const dialog = app.getByRole("alertdialog");
  await dialog.getByRole("button", { name: "キャンセル", exact: true }).press("ControlOrMeta+z");
  await expect(dialog).toBeVisible();
  await expect(app.getByRole("button", { name: "更新済み部署を編集", exact: true })).toHaveCount(1);
  await dialog.getByRole("button", { name: "削除する", exact: true }).click();
  await expect(app.getByRole("button", { name: "更新済み部署を編集", exact: true })).toHaveCount(0);
  await undo.press("ControlOrMeta+z");
  await expect(app.getByRole("button", { name: "更新済み部署を編集", exact: true })).toBeVisible();
  await redo.press("ControlOrMeta+Shift+z");
  await expect(app.getByRole("button", { name: "更新済み部署を編集", exact: true })).toHaveCount(0);
  await newName.fill("未登録の入力");
  await newName.press("ControlOrMeta+z");
  await expect(app.getByRole("button", { name: "更新済み部署を編集", exact: true })).toHaveCount(0);
  await undo.click();
  await expect(app.getByRole("button", { name: "更新済み部署を編集", exact: true })).toBeVisible();
  await expect(newName).toBeVisible();
});

test("前年の範囲入力を一操作で取り消し、分類選択と新しい入力を保持する", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "前年入力", exact: true }).click();
  const industry = app.getByRole("group", { name: "業種名", exact: true });
  const department = app.getByRole("group", { name: "部署名", exact: true });
  await selectClassification(industry, "直営自動車");
  await selectClassification(department, "部署A");
  await page.mouse.move(page.viewportSize()!.width - 10, 100);
  await settleMotion(app.locator(".home-layout"));
  const april = app.getByRole("textbox", { name: "売上高 4月の前年金額", exact: true });
  const may = app.getByRole("textbox", { name: "売上高 5月の前年金額", exact: true });
  const undo = app.getByRole("button", { name: "操作を取り消す", exact: true });
  const redo = app.getByRole("button", { name: "操作をやり直す", exact: true });
  await april.click();
  await april.evaluate(node => {
    const clipboardData = new DataTransfer(); clipboardData.setData("text/plain", "1200.125\t-0.001");
    node.dispatchEvent(new ClipboardEvent("paste", { bubbles: true, clipboardData }));
  });
  await expect(undo).toBeEnabled();
  await undo.click();
  await expect(april).toHaveValue("1000");
  await expect(may).toHaveValue("1000");
  await expect(industry.getByRole("button", { name: "直営自動車", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(department.getByRole("button", { name: "部署A", exact: true })).toHaveAttribute("aria-pressed", "true");
  await redo.click();
  await expect(april).toHaveValue("1200.125");
  await expect(may).toHaveValue("-0.001");
  await april.fill("1300.001");
  await expect(undo).toBeEnabled();
  await undo.click();
  await expect(april).toHaveValue("1200.125");
});

test("所属追加の取消で前年の無効選択を解除し、やり直し後も有効な分類で保存できる", async ({ page, app }) => {
  await page.getByLabel("テストデータ", { exact: true }).selectOption("defaults");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  const menu = app.getByRole("navigation", { name: "メインナビゲーション" });
  await menu.getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^部署マスタ/ }).click();
  const form = app.getByRole("form", { name: "部署の新規登録", exact: true });
  await form.getByRole("textbox", { name: "部署名", exact: true }).fill("所属確認部署");
  await form.getByRole("checkbox", { name: "直営自動車", exact: true }).check();
  await form.getByRole("button", { name: "登録", exact: true }).click();
  await app.getByRole("button", { name: "所属確認部署を編集", exact: true }).click();
  const choices = app.getByRole("group", { name: "所属確認部署の業種名", exact: true });
  const other = choices.getByRole("checkbox").nth(1);
  const otherName = (await other.locator("..").innerText()).trim();
  await other.check();
  await expect(app.getByRole("button", { name: "完了", exact: true })).toBeEnabled();
  await app.getByRole("button", { name: "完了", exact: true }).click();
  await menu.getByRole("button", { name: "前年入力", exact: true }).click();
  const industries = app.getByRole("group", { name: "業種名", exact: true });
  await selectClassification(app.getByRole("group", { name: "部署名", exact: true }), "所属確認部署");
  await selectClassification(industries, otherName);
  const amount = app.getByRole("textbox", { name: "売上高 4月の前年金額", exact: true });
  await expect(amount).toBeVisible();
  const undo = app.getByRole("button", { name: "操作を取り消す", exact: true });
  await undo.click();
  await expect(industries.getByRole("button", { name: otherName, exact: true })).toHaveCount(0);
  await expect(amount).toHaveCount(0);
  await app.getByRole("button", { name: "操作をやり直す", exact: true }).click();
  await expect(industries.getByRole("button", { name: otherName, exact: true })).toHaveAttribute("aria-pressed", "false");
  await expect(amount).toHaveCount(0);
  await selectClassification(industries, "直営自動車");
  await amount.fill("8.25");
  await amount.press("Enter");
  await expect(undo).toBeEnabled();
  await undo.click();
  await expect(amount).toHaveValue("0");
  await app.getByRole("button", { name: "操作をやり直す", exact: true }).click();
  await expect(amount).toHaveValue("8.25");
  await expect(app.getByRole("alert")).toHaveCount(0);
});

for (const leaveDetail of [false, true]) test(`登録取消後の画面履歴がHomeまで戻れる（一覧へ戻す=${leaveDetail}）`, async ({ app, page }) => {
  await page.getByLabel("テストデータ", { exact: true }).selectOption("defaults");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "施策一覧", exact: true }).click();
  await app.getByRole("button", { name: "施策を追加", exact: true }).click();
  await app.getByRole("textbox", { name: "施策名", exact: true }).fill("画面履歴確認");
  for (const [label, name] of ([["展開名", "コスト"], ["部署名", "部署A"], ["業種名", "直営自動車"]] as const)) await selectClassification(app.getByRole("spinbutton", { name: label, exact: true }), name);
  await app.getByRole("combobox", { name: "1行目の勘定科目", exact: true }).focus();
  await app.getByRole("combobox", { name: "1行目の勘定科目", exact: true }).selectOption("1");
  await app.getByRole("button", { name: "登録", exact: true }).click();
  await app.getByRole("button", { name: "画面履歴確認", exact: true }).click();
  if (leaveDetail) await app.getByRole("button", { name: "← 施策一覧へ戻る", exact: true }).click();
  await app.getByRole("button", { name: "操作を取り消す", exact: true }).click();
  await expect(app.getByRole("button", { name: "画面履歴確認", exact: true })).toHaveCount(0);
  const back = app.getByRole("button", { name: "前の画面に戻る", exact: true });
  await expect(back).toBeEnabled();
  for (let count = 0; count < 8 && await back.isEnabled(); count++) { await back.click(); await settleMotion(app.locator("body")); }
  await expect(app.getByRole("heading", { name: "Home", exact: true })).toBeVisible();
  await expect(back).toBeDisabled();
  const forward = app.getByRole("button", { name: "次の画面に進む", exact: true });
  await expect(forward).toBeEnabled();
  await forward.click();
  await expect(app.getByRole("heading", { name: "施策一覧", exact: true })).toBeVisible();
  await app.getByRole("button", { name: "操作をやり直す", exact: true }).click();
  await expect(app.getByRole("button", { name: "画面履歴確認", exact: true })).toBeVisible();
});
