import { test, expect, settleMotion } from "./fixtures";

test("戻る・進むの端点、別画面への分岐、施策入力の保持と履歴のリセット", async ({ app }) => {
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  const back = app.getByRole("button", { name: "前の画面に戻る", exact: true });
  const forward = app.getByRole("button", { name: "次の画面に進む", exact: true });
  await expect(back).toBeDisabled();
  await expect(forward).toBeDisabled();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  const menu = app.getByRole("navigation", { name: "メインナビゲーション" });
  await menu.getByRole("button", { name: "施策入力", exact: true }).click();
  await app.getByRole("textbox", { name: "施策名", exact: true }).fill("履歴を移動しても残る入力");
  await menu.getByRole("button", { name: "マスタ", exact: true }).click();
  await app.getByRole("button", { name: /^勘定科目マスタ/ }).click();
  await back.click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
  await back.click();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("履歴を移動しても残る入力");
  await forward.click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
  await forward.click();
  await expect(app.getByRole("heading", { name: "勘定科目マスタ", exact: true })).toBeVisible();
  await expect(forward).toBeDisabled();
  await back.click();
  await menu.getByRole("button", { name: "総原価表", exact: true }).click();
  await expect(app.getByRole("heading", { name: "総原価表", exact: true })).toBeVisible();
  await expect(forward).toBeDisabled();
  await back.click();
  await expect(app.getByRole("heading", { name: "マスタ", exact: true })).toBeVisible();
  // Opening the current screen must not add a duplicate history entry.
  await menu.getByRole("button", { name: "マスタ", exact: true }).click();
  await back.click();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("履歴を移動しても残る入力");
  await back.click();
  await expect(app.getByRole("main", { name: "ホーム", exact: true })).toBeVisible();
  await expect(back).toBeDisabled();
  await app.getByRole("button", { name: "ファイルを閉じる", exact: true }).click();
  await app.getByRole("alertdialog").getByRole("button", { name: "閉じる", exact: true }).click();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await expect(back).toBeDisabled();
  await expect(forward).toBeDisabled();
});

test("別々の施策詳細と戻り先を復元し、保存失敗中には移動を止める", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html?data=full");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await page.getByLabel("ファイル操作", { exact: true }).selectOption("save-failure");
  await expect(app.getByRole("heading", { name: "Triadichrome", exact: true })).toBeVisible();
  await settleMotion(app.locator("body"));
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  const menu = app.getByRole("navigation", { name: "メインナビゲーション" });
  const back = app.getByRole("button", { name: "前の画面に戻る", exact: true });
  const forward = app.getByRole("button", { name: "次の画面に進む", exact: true });
  await menu.getByRole("button", { name: "施策一覧", exact: true }).click();
  await app.getByRole("button", { name: "既存商品の販売拡大", exact: true }).click();
  await app.getByRole("button", { name: "施策入力を開く", exact: true }).click();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("既存商品の販売拡大");
  await menu.getByRole("button", { name: "展開表", exact: true }).click();
  await app.getByRole("button", { name: "保守サービスの新規契約", exact: true }).click();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("保守サービスの新規契約");
  await back.click();
  await expect(app.getByRole("heading", { name: "展開表", exact: true })).toBeVisible();
  await back.click();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("既存商品の販売拡大");
  await expect(app.getByRole("button", { name: "← 施策一覧へ戻る", exact: true })).toBeVisible();
  await forward.click();
  await expect(app.getByRole("heading", { name: "展開表", exact: true })).toBeVisible();
  await forward.click();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("保守サービスの新規契約");
  await expect(app.getByRole("button", { name: "← 展開表へ戻る", exact: true })).toBeVisible();
  await app.getByRole("textbox", { name: "施策名", exact: true }).fill("保存失敗で保持する名前");
  await expect(app.getByRole("alert")).toContainText("テスト用の保存失敗です。");
  await expect(back).toBeDisabled();
  await expect(forward).toBeDisabled();
  await expect(app.getByRole("textbox", { name: "施策名", exact: true })).toHaveValue("保存失敗で保持する名前");
  await settleMotion(app.locator("body"));
});
