import ExcelJS from "exceljs";
import JSZip from "jszip";
import { readFile } from "node:fs/promises";
import { test, expect } from "./fixtures";

test("表と前年フォーマットの出力、確認・取消・一括取り込み・操作取消", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "入出力", exact: true }).click();
  await expect(app.getByRole("heading", { name: "入出力", exact: true })).toBeVisible();
  const reportPromise = page.waitForEvent("download");
  await app.getByRole("button", { name: "選んだ表を出力", exact: true }).click();
  const report = await reportPromise;
  const wb = new ExcelJS.Workbook(); await wb.xlsx.load(await readFile((await report.path())!) as unknown as ExcelJS.Buffer);
  expect(wb.worksheets.map(s => s.name)).toEqual(["総原価表", "施策一覧", "展開表", "計算元"]);
  expect(wb.getWorksheet("総原価表")!.getCell("B5").formula).toBeTruthy();
  await app.getByRole("checkbox", { name: "直営自動車・部署A", exact: true }).check();
  await app.getByRole("checkbox", { name: "自動車取扱・部署B", exact: true }).check();
  const templatePromise = page.waitForEvent("download");
  await app.getByRole("button", { name: "フォーマットを出力", exact: true }).click();
  const download = await templatePromise;
  const template = new ExcelJS.Workbook(); await template.xlsx.load(await readFile((await download.path())!) as unknown as ExcelJS.Buffer);
  expect(template.worksheets.filter(s => s.state === "visible")).toHaveLength(2);
  template.worksheets[0]!.getCell("C4").value = null;
  template.worksheets[0]!.getCell("D4").value = 0;
  template.worksheets[0]!.getCell("E4").value = -123.456;
  const file = { name: "前年入力.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(await template.xlsx.writeBuffer()) };
  const hostile = await JSZip.loadAsync(file.buffer);
  const sheetXml = await hostile.file("xl/worksheets/sheet1.xml")!.async("string");
  hostile.file("xl/worksheets/sheet1.xml", sheetXml.replace("</worksheet>", '<mergeCells count="1"><mergeCell ref="A100:IV355"/></mergeCells></worksheet>'));
  await app.locator('input[type="file"]').setInputFiles({ ...file, buffer: await hostile.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }) });
  await expect(app.getByRole("alert")).toContainText("不要な結合");
  await expect(app.getByRole("button", { name: "前の画面に戻る", exact: true })).toBeEnabled();
  await app.locator('input[type="file"]').setInputFiles(file);
  const preview = app.getByRole("region", { name: "前年金額の変更確認" });
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 2件");
  await expect(preview.getByText("-123.456", { exact: true })).toBeVisible();
  await expect(app.getByRole("button", { name: "前の画面に戻る", exact: true })).toBeDisabled();
  await preview.getByRole("button", { name: "キャンセル", exact: true }).click();
  await expect(preview).toHaveCount(0);
  const frame = page.frames()[1]!;
  const zone = frame.locator(".io-previous-panel");
  const transfer = await frame.evaluateHandle(({ bytes, name }) => {
    const data = new DataTransfer();
    data.items.add(new File([new Uint8Array(bytes)], name));
    return data;
  }, { bytes: [...file.buffer], name: file.name });
  const text = await frame.evaluateHandle(() => {
    const data = new DataTransfer(); data.setData("text/plain", "text"); return data;
  });
  await zone.dispatchEvent("dragover", { dataTransfer: text });
  await expect(zone).not.toHaveClass(/is-drag-active/);
  await zone.dispatchEvent("dragenter", { dataTransfer: transfer });
  await expect(zone).toHaveClass(/is-drag-active/);
  await expect(app.getByRole("heading", { name: "ここにドロップして取り込む" })).toBeVisible();
  await zone.evaluate(node => node.dispatchEvent(new DragEvent("dragleave", { bubbles: true, relatedTarget: node.querySelector("button") })));
  await expect(zone).toHaveClass(/is-drag-active/);
  await zone.dispatchEvent("dragleave", { relatedTarget: null });
  await expect(zone).not.toHaveClass(/is-drag-active/);
  await zone.dispatchEvent("dragover", { dataTransfer: transfer });
  await zone.dispatchEvent("drop", { dataTransfer: transfer });
  await expect(zone).not.toHaveClass(/is-drag-active/);
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 2件");
  const multiple = await frame.evaluateHandle(() => {
    const data = new DataTransfer();
    data.items.add(new File(["invalid"], "a.xlsx")); data.items.add(new File(["invalid"], "b.xlsx"));
    return data;
  });
  await zone.dispatchEvent("drop", { dataTransfer: multiple });
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 2件");
  await expect(app.getByRole("alert")).toHaveCount(0);
  await preview.getByRole("button", { name: "キャンセル", exact: true }).click();
  await zone.dispatchEvent("drop", { dataTransfer: multiple });
  await expect(app.getByRole("alert")).toContainText("一つずつ");
  await expect(preview).toHaveCount(0);
  const invalid = await frame.evaluateHandle(() => {
    const data = new DataTransfer(); data.items.add(new File(["invalid"], "a.txt")); return data;
  });
  await zone.dispatchEvent("drop", { dataTransfer: invalid });
  await expect(app.getByRole("alert")).toContainText(".xlsx");
  await expect(preview).toHaveCount(0);
  await zone.dispatchEvent("drop", { dataTransfer: transfer });
  await preview.getByRole("button", { name: "確認した内容を取り込む", exact: true }).click();
  await expect(app.getByText("前年金額を取り込みました。", { exact: true })).toBeVisible();
  await expect(preview).toHaveCount(0);
  await app.getByRole("button", { name: "操作を取り消す", exact: true }).click();
  await expect(app.getByText("操作を取り消しました。", { exact: true })).toBeVisible();
  await app.locator('input[type="file"]').setInputFiles(file);
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 2件");
  await preview.getByRole("button", { name: "キャンセル", exact: true }).click();
  template.worksheets[0]!.getCell("E4").value = "不正な金額";
  await app.locator('input[type="file"]').setInputFiles({ ...file, buffer: Buffer.from(await template.xlsx.writeBuffer()) });
  await expect(app.getByRole("alert")).toContainText("小数点以下3桁");
  await expect(preview).toHaveCount(0);
});

test("前年取り込みの保存失敗で確認内容を保持する", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await page.getByLabel("ファイル操作").selectOption("save-failure");
  await expect(app.getByRole("heading", { name: "Triadichrome", exact: true })).toBeVisible();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "入出力", exact: true }).click();
  await app.getByRole("checkbox", { name: "直営自動車・部署A", exact: true }).check();
  const promise = page.waitForEvent("download");
  await app.getByRole("button", { name: "フォーマットを出力", exact: true }).click();
  const download = await promise;
  const wb = new ExcelJS.Workbook(); await wb.xlsx.load(await readFile((await download.path())!) as unknown as ExcelJS.Buffer);
  wb.worksheets[0]!.getCell("C4").value = 123.456;
  await app.locator('input[type="file"]').setInputFiles({ name: "前年.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(await wb.xlsx.writeBuffer()) });
  await app.getByRole("button", { name: "確認した内容を取り込む", exact: true }).click();
  await expect(app.getByRole("alert")).toContainText("保存失敗");
  await expect(app.getByRole("button", { name: "保存を再試行して取り込む", exact: true })).toBeEnabled();
  await expect(app.getByRole("region", { name: "前年金額の変更確認" }).getByText("123.456", { exact: true })).toBeVisible();
  await expect(app.getByRole("button", { name: "操作を取り消す", exact: true })).toBeDisabled();
  await app.getByRole("region", { name: "前年金額の変更確認" }).getByRole("button", { name: "キャンセル", exact: true }).click();
});

test("前年フォーマットの上限超過で出力せず、選択を減らして読み戻せる", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html?data=previous-export-limit");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "入出力", exact: true }).click();
  const choices = app.getByRole("group", { name: "フォーマットに含める業種・部署" }).getByRole("checkbox");
  await expect(choices).toHaveCount(18);
  for (const choice of await choices.all()) await choice.check();
  const downloads: string[] = []; page.on("download", file => downloads.push(file.suggestedFilename()));
  await app.getByRole("button", { name: "フォーマットを出力", exact: true }).click();
  await expect(app.getByRole("alert")).toContainText("組み合わせを減らし、別ファイルに分けて");
  expect(downloads).toEqual([]);
  await expect(choices.first()).toBeChecked();
  await expect(app.getByRole("button", { name: "前の画面に戻る", exact: true })).toBeEnabled();
  await app.getByRole("button", { name: "通知を閉じる", exact: true }).click();
  // A small split keeps the browser round trip quick; the 17-pair boundary is tested in core.
  for (const choice of (await choices.all()).slice(1)) await choice.uncheck();
  const promise = page.waitForEvent("download");
  await app.getByRole("button", { name: "フォーマットを出力", exact: true }).click();
  const file = await promise;
  const bytes = await readFile((await file.path())!);
  await expect(app.getByText("前年入力フォーマットを出力しました。", { exact: true })).toBeVisible();
  await app.locator('input[type="file"]').setInputFiles({ name: "前年.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: bytes });
  await expect(app.getByText("変更する金額がありません。", { exact: true })).toBeVisible();
  const wb = new ExcelJS.Workbook(); await wb.xlsx.load(bytes as unknown as ExcelJS.Buffer);
  expect(wb.worksheets[0]!.getCell("C4").value).toBe(123.456);
  wb.worksheets[0]!.getCell("C4").value = 0;
  await app.locator('input[type="file"]').setInputFiles({ name: "前年.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(await wb.xlsx.writeBuffer()) });
  const preview = app.getByRole("region", { name: "前年金額の変更確認" });
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 1件");
  await expect(preview.getByText("123.456", { exact: true })).toBeVisible();
  await preview.getByRole("button", { name: "確認した内容を取り込む", exact: true }).click();
  await expect(app.getByText("前年金額を取り込みました。", { exact: true })).toBeVisible();
});
