import ExcelJS from "exceljs";
import JSZip from "jszip";
import { readFile } from "node:fs/promises";
import { test, expect } from "./fixtures";

test("表と前年フォーマットの出力、確認・取消・一括取り込み・操作取消", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "入出力", exact: true }).click();
  await expect(app.getByRole("heading", { name: "入出力", exact: true })).toBeVisible();
  const reportPromise = page.waitForEvent("download");
  await app.getByRole("button", { name: "選んだ表を出力", exact: true }).click();
  const report = await reportPromise;
  const archive = await JSZip.loadAsync(await readFile((await report.path())!));
  expect(archive.file("xl/metadata.xml")).not.toBeNull();
  // ExcelJS 4.4 cannot read calculation-column children. Inspect the original
  // native metadata, then remove only those children from the reader's copy.
  for (const file of Object.values(archive.files).filter(f => /^xl\/tables\/table\d+\.xml$/.test(f.name)))
    archive.file(file.name, (await file.async("string")).replace(/<calculatedColumnFormula>[\s\S]*?<\/calculatedColumnFormula>/g, ""));
  const wb = new ExcelJS.Workbook(); await wb.xlsx.load(await archive.generateAsync({ type: "nodebuffer" }) as unknown as ExcelJS.Buffer);
  expect(wb.worksheets.slice(0, 3).map(s => s.name)).toEqual(["総原価表", "施策一覧", "展開表"]);
  expect(wb.getWorksheet("施策入力")).toBeDefined();
  expect(wb.getWorksheet("施策金額")).toBeDefined();
  expect(wb.getWorksheet("科目マスタ")).toBeDefined();
  expect(wb.getWorksheet("総原価表")!.getCell("B5").formula).toBeTruthy();
  await app.getByRole("checkbox", { name: "直営自動車・部署A", exact: true }).check();
  await app.getByRole("checkbox", { name: "自動車取扱・部署B", exact: true }).check();
  const templatePromise = page.waitForEvent("download");
  await app.getByRole("button", { name: "フォーマットを出力", exact: true }).click();
  const download = await templatePromise;
  const template = new ExcelJS.Workbook(); await template.xlsx.load(await readFile((await download.path())!) as unknown as ExcelJS.Buffer);
  expect(template.worksheets.filter(s => s.state === "visible")).toHaveLength(2);
  template.worksheets[0]!.getCell("C4").value = null;
  template.worksheets[0]!.getCell("D4").value = 0;
  template.worksheets[0]!.getCell("E4").value = -123.456;
  const file = { name: "前年入力.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(await template.xlsx.writeBuffer()) };
  await app.locator('input[type="file"]').setInputFiles(file);
  const preview = app.getByRole("region", { name: "前年金額の変更確認" });
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 2件");
  await expect(preview.getByText("-123.456", { exact: true })).toBeVisible();
  await expect(app.getByRole("button", { name: "前の画面に戻る", exact: true })).toBeDisabled();
  await preview.getByRole("button", { name: "キャンセル", exact: true }).click();
  await expect(preview).toHaveCount(0);
  await app.locator('input[type="file"]').setInputFiles(file);
  await preview.getByRole("button", { name: "確認した内容を取り込む", exact: true }).click();
  await expect(app.getByText("前年金額を取り込みました。", { exact: true })).toBeVisible();
  await expect(preview).toHaveCount(0);
  await app.getByRole("button", { name: "操作を取り消す", exact: true }).click();
  await expect(app.getByText("操作を取り消しました。", { exact: true })).toBeVisible();
  await app.locator('input[type="file"]').setInputFiles(file);
  await expect(preview.getByRole("heading")).toHaveText("変更内容 · 2件");
  await preview.getByRole("button", { name: "キャンセル", exact: true }).click();
  template.worksheets[0]!.getCell("E4").value = "不正な金額";
  await app.locator('input[type="file"]').setInputFiles({ ...file, buffer: Buffer.from(await template.xlsx.writeBuffer()) });
  await expect(app.getByRole("alert")).toContainText("小数点以下3桁");
  await expect(preview).toHaveCount(0);
});

test("前年取り込みの保存失敗で確認内容を保持する", async ({ page, app }) => {
  await page.goto("/tests/ui/preview.html");
  await expect(page.getByRole("status")).toHaveText("操作できます");
  await page.getByLabel("ファイル操作").selectOption("save-failure");
  await expect(app.getByRole("heading", { name: "Triadichrome", exact: true })).toBeVisible();
  await app.getByRole("button", { name: "ファイルを開く", exact: true }).click();
  await app.getByRole("button", { name: "サイドバーを開く", exact: true }).click();
  await app.getByRole("navigation", { name: "メインナビゲーション" }).getByRole("button", { name: "入出力", exact: true }).click();
  await app.getByRole("checkbox", { name: "直営自動車・部署A", exact: true }).check();
  const promise = page.waitForEvent("download");
  await app.getByRole("button", { name: "フォーマットを出力", exact: true }).click();
  const download = await promise;
  const wb = new ExcelJS.Workbook(); await wb.xlsx.load(await readFile((await download.path())!) as unknown as ExcelJS.Buffer);
  wb.worksheets[0]!.getCell("C4").value = 123.456;
  await app.locator('input[type="file"]').setInputFiles({ name: "前年.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from(await wb.xlsx.writeBuffer()) });
  await app.getByRole("button", { name: "確認した内容を取り込む", exact: true }).click();
  await expect(app.getByRole("alert")).toContainText("保存失敗");
  await expect(app.getByRole("button", { name: "保存を再試行して取り込む", exact: true })).toBeEnabled();
  await expect(app.getByRole("region", { name: "前年金額の変更確認" }).getByText("123.456", { exact: true })).toBeVisible();
  await expect(app.getByRole("button", { name: "操作を取り消す", exact: true })).toBeDisabled();
  await app.getByRole("region", { name: "前年金額の変更確認" }).getByRole("button", { name: "キャンセル", exact: true }).click();
});
