import { createHash } from "node:crypto";
import { readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import initSqlJs from "sql.js";
import ts from "typescript";
import { projectRoot } from "./paths.mjs";
import { withNodeBundle } from "./node-bundle.mjs";

const extension = "Triadichrome-extension/src/extension/";
const schemaPath = "Triadichrome-extension/src/core/storage/dataMapSchema.generated.ts";
const reviewPath = extension + "screenDataReview.json";
const digest = text => createHash("sha256").update(text).digest("hex");
const quote = identifier => '"' + identifier.replaceAll('"', '""') + '"';
export function describeSchema(database) {
  return (database.exec("SELECT name FROM sqlite_master WHERE type = 'table' AND name != 'sqlite_sequence' ORDER BY name")[0]?.values ?? []).map(([name]) => {
    const references = database.exec(`PRAGMA foreign_key_list(${quote(name)})`)[0]?.values ?? [];
    return { name, columns: database.exec(`PRAGMA table_info(${quote(name)})`)[0].values.map(column => ({ name: column[1],
      ...(references.some(row => row[3] === column[1]) ? { reference: references.filter(row => row[3] === column[1]).map(row => `${row[2]}.${row[4]}`).join(", ") } : {}) })) };
  });
}
async function schemaText() {
  return withNodeBundle("scripts/data-map-schema.ts", async ({ TRIADIC_SCHEMA_SQL, DATA_HISTORY_SQL }) => {
    const SQL = await initSqlJs({ locateFile: name => path.join(projectRoot, "node_modules/sql.js/dist", name) });
    const database = new SQL.Database();
    try {
      database.run(TRIADIC_SCHEMA_SQL + DATA_HISTORY_SQL);
      return "// Generated by scripts/data-map.mjs from the saved schema. Do not edit.\nexport const dataMapSchema = " + JSON.stringify(describeSchema(database), null, 2) + " as const;\n";
    } finally { database.close(); }
  });
}
async function resolveModule(owner, specifier) {
  if (!specifier.startsWith(".")) return null;
  const base = path.resolve(projectRoot, path.dirname(owner), specifier);
  for (const suffix of [".ts", ".tsx", "/index.ts", "/index.tsx"]) {
    try { await access(base + suffix); return path.relative(projectRoot, base + suffix); } catch { /* not a TypeScript module */ }
  }
  return null;
}
const readSource = file => readFile(path.join(projectRoot, file), "utf8");
async function sourceModule(file, read = readSource) {
  const text = await read(file);
  const source = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, file.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
  const imports = new Map();
  const dependencies = new Set();
  for (const statement of source.statements) {
    if (ts.isExportDeclaration(statement) && !statement.isTypeOnly && statement.moduleSpecifier && ts.isStringLiteral(statement.moduleSpecifier)) {
      const target = await resolveModule(file, statement.moduleSpecifier.text);
      if (target) dependencies.add(target);
    }
    if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier) || statement.importClause?.isTypeOnly) continue;
    const target = await resolveModule(file, statement.moduleSpecifier.text);
    if (!target) continue;
    dependencies.add(target);
    const clause = statement.importClause;
    if (clause?.name) imports.set(clause.name.text, target);
    if (clause?.namedBindings && ts.isNamespaceImport(clause.namedBindings)) imports.set(clause.namedBindings.name.text, target);
    if (clause?.namedBindings && ts.isNamedImports(clause.namedBindings))
      for (const item of clause.namedBindings.elements) if (!item.isTypeOnly) imports.set(item.name.text, target);
  }
  return { text, source, imports, dependencies };
}
export async function screenImplementations(read = readSource) {
  const cache = new Map();
  const moduleFor = file => {
    if (!cache.has(file)) cache.set(file, sourceModule(file, read));
    return cache.get(file);
  };
  const home = await moduleFor(extension + "HomePage.tsx");
  const cases = [];
  const visit = node => {
    if (ts.isSwitchStatement(node) && node.expression.getText(home.source) === "displayed.page")
      cases.push(...node.caseBlock.clauses.filter(ts.isCaseClause));
    ts.forEachChild(node, visit);
  };
  visit(home.source);
  const result = {};
  for (const item of cases) {
    const page = ts.isStringLiteral(item.expression) ? item.expression.text : null;
    if (!page || ["home", "master"].includes(page)) continue;
    const seeds = new Set(["Triadichrome-extension/src/core/storage/readPlan.ts"]);
    const identifiers = node => {
      if (ts.isIdentifier(node) && home.imports.has(node.text)) seeds.add(home.imports.get(node.text));
      ts.forEachChild(node, identifiers);
    };
    identifiers(item);
    const sources = new Map();
    const collect = async file => {
      if (sources.has(file) || file === schemaPath) return;
      const module = await moduleFor(file);
      sources.set(file, digest(module.text));
      for (const target of module.dependencies) await collect(target);
    };
    for (const seed of seeds) await collect(seed);
    result[page] = digest(JSON.stringify({ parent: digest(home.text), wiring: item.getText(home.source), sources: [...sources].sort(([a], [b]) => a.localeCompare(b)) }));
  }
  if (Object.keys(result).length === 0) throw new Error("画面の切り替え実装を取得できません。");
  return result;
}
export function staleScreens(review, implementations, screens) {
  const descriptions = new Map(screens.map(screen => [screen.page, digest(JSON.stringify(screen))]));
  return [...new Set([...Object.keys(implementations), ...Object.keys(review), ...descriptions.keys()])].filter(page =>
    !implementations[page] || !descriptions.has(page) || review[page]?.implementation !== implementations[page] || review[page]?.description !== descriptions.get(page));
}
export async function mechanismImplementations(topics, read = readSource) {
  const cache = new Map();
  const moduleFor = file => {
    if (!cache.has(file)) cache.set(file, sourceModule(file, read));
    return cache.get(file);
  };
  const result = {};
  for (const topic of topics) {
    if (!topic.sources.length || result[topic.id]) throw new Error(`仕組みの対象または根拠が不正です: ${topic.id}`);
    const sources = new Map();
    const collect = async file => {
      if (sources.has(file) || file === extension + "mechanismModel.ts") return;
      if (!file.startsWith("Triadichrome-extension/src/") || file.includes("..")) throw new Error(`実装参照が不正です: ${file}`);
      const module = await moduleFor(file);
      sources.set(file, digest(module.text));
      for (const dependency of module.dependencies) await collect(dependency);
    };
    for (const source of [...topic.sources, extension + "MechanismMap.tsx", extension + "HomeRelationsPage.tsx"]) await collect(source);
    result[topic.id] = digest(JSON.stringify([...sources].sort(([a], [b]) => a.localeCompare(b))));
  }
  return result;
}
async function checkMechanisms(args) {
  const file = path.join(projectRoot, extension + "mechanismReview.json");
  await withNodeBundle(extension + "mechanismModel.ts", async ({ mechanisms }) => {
    for (const kind of ["calculation", "process"]) {
      if (!mechanisms.some(topic => topic.kind === kind)) throw new Error(`仕組みの表示対象がありません: ${kind}`);
    }
    const implementations = await mechanismImplementations(mechanisms);
    let recorded = {};
    try { recorded = JSON.parse(await readFile(file, "utf8")); } catch (error) { if (error.code !== "ENOENT") throw error; }
    if (args.includes("--review-mechanisms")) {
      const selected = args.filter(arg => !arg.startsWith("--"));
      for (const id of selected.length ? selected : Object.keys(implementations)) {
        const topic = mechanisms.find(topic => topic.id === id);
        if (!topic) throw new Error(`仕組みの対象がありません: ${id}`);
        recorded[id] = { implementation: implementations[id], description: digest(JSON.stringify({ ...topic, page: topic.id })) };
      }
      for (const id of Object.keys(recorded)) if (!implementations[id]) delete recorded[id];
      await writeFile(file, JSON.stringify(recorded, null, 2) + "\n");
    }
    const stale = staleScreens(recorded, implementations, mechanisms.map(topic => ({ ...topic, page: topic.id })));
    if (stale.length) throw new Error(`計算・処理の開示内容を確認してください: ${stale.join(", ")}\n実装と説明を照合した後、npm run mechanism-map:review -- <対象ID> で確認済みとして記録してください。`);
  });
}
async function main(args) {
  const check = args.includes("--check"), review = args.includes("--review");
  const generated = await schemaText();
  let current = "";
  try { current = await readFile(path.join(projectRoot, schemaPath), "utf8"); } catch { /* first generation */ }
  if (current !== generated) {
    if (check) throw new Error("保存構造の対応情報が古くなっています。npm run data-map:generate を実行してください。");
    await writeFile(path.join(projectRoot, schemaPath), generated);
  }
  if (args.includes("--review-mechanisms")) {
    await checkMechanisms(args);
    console.log("mechanism map ok: descriptions match reviewed implementations");
    return;
  }
  const implementations = await screenImplementations();
  await withNodeBundle("Triadichrome-extension/src/extension/screenDataModel.ts", async ({ screenData }) => {
    let recorded = {};
    try { recorded = JSON.parse(await readFile(path.join(projectRoot, reviewPath), "utf8")); } catch { /* first review */ }
    if (review) {
      const selected = args.filter(arg => !arg.startsWith("--"));
      const pages = selected.length ? selected : Object.keys(implementations);
      for (const page of pages) {
        const screen = screenData.find(item => item.page === page);
        if (!screen || !implementations[page]) throw new Error(`画面の対応情報がありません: ${page}`);
        recorded[page] = { implementation: implementations[page], description: digest(JSON.stringify(screen)) };
      }
      for (const page of Object.keys(recorded)) if (!implementations[page]) delete recorded[page];
      await writeFile(path.join(projectRoot, reviewPath), JSON.stringify(recorded, null, 2) + "\n");
    }
    const stale = staleScreens(recorded, implementations, screenData);
    if (stale.length) throw new Error(`画面とデータの対応情報を確認してください: ${stale.join(", ")}\n実装・対応項目・計算説明を照合した後、npm run data-map:review -- <画面ID> で確認済みとして記録してください。`);
  });
  if (!review) await checkMechanisms(args);
  console.log("data map ok: schema generated from source; screen descriptions match reviewed implementations");
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { await main(process.argv.slice(2)); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
