import { verifyCostCancellation } from "../tests/cost-cancellation.mjs";
import { verifyAggregationOrder } from "../tests/aggregation-order.mjs";
import { verifyFileRecovery } from "../tests/file-recovery.mjs";
import { verifyExpansionTableView } from "../tests/expansion-table-view.mjs";
import { verifyUnifiedMaster } from "../tests/unified-master.mjs";
import { verifyInitiativeListRendering } from '../tests/initiative-list-rendering.mjs';
import { verifyPerformanceData } from '../tests/performance-data.mjs';
import { verifySchemaBoundary } from "../tests/schema-boundary.mjs";
import { verifyYenPrecision } from "../tests/yen-precision.mjs";
import { verifyPeriodTables } from "../tests/period-tables.mjs";
import { verifySpreadsheetIO } from "../tests/spreadsheet-io.mjs";
import { verifyCostComparison } from "../tests/cost-comparison.mjs";
import { verifyHomeMotion } from "../tests/home-graph-motion.mjs";
import { verifyPlanSession } from "../tests/plan-session.mjs";
import { verifySavedOperations } from "../tests/saved-operations.mjs";
import { verifyInitiativeGrid } from "../tests/initiative-grid.mjs";
import { verifyDataHistory } from "../tests/data-history.mjs";
import { verifyPreviousGrid } from "../tests/previous-grid.mjs";
import { verifyInitiativeData } from "../tests/initiative-data.mjs";
import { verifyDetails } from "../tests/details.mjs";
import { verifyFileBoundaries } from "../tests/file-boundaries.mjs";
import { verifyDepartmentData } from "../tests/department-data.mjs";
import { verifyPeriodData } from "../tests/period-data.mjs";
import { verifyIndustryData } from "../tests/industry-data.mjs";
import { verifyExpansionData } from "../tests/expansion-data.mjs";
import { verifyHomeMasterCoverage } from "../tests/home-master-coverage.mjs";
import { verifyDefaultCostData } from "../tests/default-cost-data.mjs";
import { verifyExpansionTable } from "../tests/expansion-table.mjs";
import { verifyRecentFile } from "../tests/recent-file.mjs";
import { verifyAutoSave } from "../tests/auto-save.mjs";
import { verifyAggregationData } from "../tests/aggregation-data.mjs";
import { verifySamplePlan } from "../tests/sample-plan.mjs";
import { verifySingleYearPlan } from "../tests/single-year-plan.mjs";
import { verifyInitiativeTotals } from "../tests/initiative-totals.mjs";
import { verifyTableSort } from "../tests/table-sort.mjs";
import { verifyInitiativeSort } from "../tests/initiative-sort.mjs";
import { verifyStartMonths } from "../tests/start-months.mjs";
import { withNodeBundle } from "./node-bundle.mjs";
import { projectRoot as root } from "./paths.mjs";
await withNodeBundle("tests/core-api.ts", async production => {
  const api = { ...production, createTriadicDatabase: (year = 2026) => production.createTriadicDatabase(year) };
  await verifyFileRecovery(api);
  await verifyUnifiedMaster(api);
  await verifySchemaBoundary(api);
  await verifyYenPrecision(api);
  await verifyCostCancellation(api);
  verifyAggregationOrder(api);
  await verifyCostComparison(api);
  await verifyPeriodTables(api);
  await verifySpreadsheetIO(api);
  verifyHomeMotion(api);
  verifyPreviousGrid(api);
  verifyInitiativeGrid(api);
  verifyHomeMasterCoverage(api);
  await verifySingleYearPlan(api);
  await verifyStartMonths(api);
  verifyInitiativeSort(api);
  verifyTableSort(api);
  verifyInitiativeTotals(api);
  await verifyDetails(api);
  await verifyInitiativeData({ ...api, createTriadicDatabase: () => api.createCurrentEmptyTestPlan(2026) }, root);
  await verifyFileBoundaries(api);
  await verifyDepartmentData(api);
  await verifyPeriodData(api);
  await verifyIndustryData(api);
  await verifyExpansionData(api);
  await verifyDefaultCostData(api);
  await verifyExpansionTable(api);
  await verifyAggregationData({ ...api, createTriadicDatabase: () => api.createCurrentEmptyTestPlan(2026) });
  await verifyAutoSave(api);
  await verifyDataHistory(api);
  await verifyPlanSession(api);
  await verifySavedOperations(api);
  await verifyRecentFile(api);
  await verifySamplePlan(api);
  await verifyPerformanceData(api, root);
});

await withNodeBundle("tests/performance-api.ts", verifyInitiativeListRendering);
await withNodeBundle("tests/performance-api.ts", verifyExpansionTableView);
