import { verifyHomeMotion } from "../tests/home-graph-motion.mjs";
import { verifyPlanSession } from "../tests/plan-session.mjs";
import { verifyInitiativeGrid } from "../tests/initiative-grid.mjs";
import { verifyDataHistory } from "../tests/data-history.mjs";
import { verifyPreviousGrid } from "../tests/previous-grid.mjs";
import { verifyInitiativeData } from "../tests/initiative-data.mjs";
import { verifyDetails } from "../tests/details.mjs";
import { verifyFileBoundaries } from "../tests/file-boundaries.mjs";
import { verifyDepartmentData } from "../tests/department-data.mjs";
import { verifyPeriodData } from "../tests/period-data.mjs";
import { verifyIndustryData } from "../tests/industry-data.mjs";
import { verifyExpansionData } from "../tests/expansion-data.mjs";
import { verifyHomeMasterCoverage } from "../tests/home-master-coverage.mjs";
import { verifyDefaultCostData } from "../tests/default-cost-data.mjs";
import { verifyExpansionTable } from "../tests/expansion-table.mjs";
import { verifyRecentFile } from "../tests/recent-file.mjs";
import { verifyAutoSave } from "../tests/auto-save.mjs";
import { verifyAggregationData } from "../tests/aggregation-data.mjs";
import { verifySamplePlan } from "../tests/sample-plan.mjs";
import { verifySingleYearPlan } from "../tests/single-year-plan.mjs";
import { withNodeBundle } from "./node-bundle.mjs";
import { projectRoot as root } from "./paths.mjs";
await withNodeBundle("tests/core-api.ts", async production => {
  const api = { ...production, createTriadicDatabase: (year = 2026) => production.createTriadicDatabase(year) };
  verifyHomeMotion(api);
  verifyPreviousGrid(api);
  verifyInitiativeGrid(api);
  verifyHomeMasterCoverage(api);
  await verifySingleYearPlan(api);
  await verifyDetails(api);
  await verifyInitiativeData({ ...api, createTriadicDatabase: () => api.createCurrentEmptyTestPlan(2026) }, root);
  await verifyFileBoundaries(api);
  await verifyDepartmentData(api);
  await verifyPeriodData(api);
  await verifyIndustryData(api);
  await verifyExpansionData(api);
  await verifyDefaultCostData(api);
  await verifyExpansionTable(api);
  await verifyAggregationData({ ...api, createTriadicDatabase: () => api.createCurrentEmptyTestPlan(2026) });
  await verifyAutoSave(api);
  await verifyDataHistory(api);
  await verifyPlanSession(api);
  await verifyRecentFile(api);
  await verifySamplePlan(api);
});
